#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WFTRAMITES")]
	public partial class WFTRAMITESDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public WFTRAMITESDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WFTRAMITESConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WFTRAMITESDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WFTRAMITESDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WFTRAMITESDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WFTRAMITESDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COORDENADAS_MANIFESTACION_AVALUO> COORDENADAS_MANIFESTACION_AVALUO
		{
			get
			{
				return this.GetTable<COORDENADAS_MANIFESTACION_AVALUO>();
			}
		}
		
		public System.Data.Linq.Table<FOLIOPAGOAVALUO> FOLIOPAGOAVALUO
		{
			get
			{
				return this.GetTable<FOLIOPAGOAVALUO>();
			}
		}
		
		public System.Data.Linq.Table<SeguimientoTramite> SeguimientoTramite
		{
			get
			{
				return this.GetTable<SeguimientoTramite>();
			}
		}
		
		public System.Data.Linq.Table<SIS_TRACAT_ABSTENCIONES> SIS_TRACAT_ABSTENCIONES
		{
			get
			{
				return this.GetTable<SIS_TRACAT_ABSTENCIONES>();
			}
		}
		
		public System.Data.Linq.Table<Tramite> Tramite
		{
			get
			{
				return this.GetTable<Tramite>();
			}
		}
		
		public System.Data.Linq.Table<SIS_TRACAT_MC> SIS_TRACAT_MC
		{
			get
			{
				return this.GetTable<SIS_TRACAT_MC>();
			}
		}
		
		public System.Data.Linq.Table<SIS_TRACAT_AC> SIS_TRACAT_AC
		{
			get
			{
				return this.GetTable<SIS_TRACAT_AC>();
			}
		}
		
		public System.Data.Linq.Table<SIS_TRACAT_SOLICITUD_MC_AV> SIS_TRACAT_SOLICITUD_MC_AV
		{
			get
			{
				return this.GetTable<SIS_TRACAT_SOLICITUD_MC_AV>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COORDENADAS_MANIFESTACION_AVALUO")]
	public partial class COORDENADAS_MANIFESTACION_AVALUO
	{
		
		private int _ID;
		
		private string _CVE_CAT_ORI;
		
		private string _STATUSREGISTROTABLA;
		
		private string _LATITUD;
		
		private string _LONGITUD;
		
		private string _UTM_X;
		
		private string _UTM_Y;
		
		public COORDENADAS_MANIFESTACION_AVALUO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(17)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(50)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATITUD", DbType="NVarChar(50)")]
		public string LATITUD
		{
			get
			{
				return this._LATITUD;
			}
			set
			{
				if ((this._LATITUD != value))
				{
					this._LATITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LONGITUD", DbType="NVarChar(50)")]
		public string LONGITUD
		{
			get
			{
				return this._LONGITUD;
			}
			set
			{
				if ((this._LONGITUD != value))
				{
					this._LONGITUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTM_X", DbType="NVarChar(50)")]
		public string UTM_X
		{
			get
			{
				return this._UTM_X;
			}
			set
			{
				if ((this._UTM_X != value))
				{
					this._UTM_X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTM_Y", DbType="NVarChar(50)")]
		public string UTM_Y
		{
			get
			{
				return this._UTM_Y;
			}
			set
			{
				if ((this._UTM_Y != value))
				{
					this._UTM_Y = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOLIOPAGOAVALUO")]
	public partial class FOLIOPAGOAVALUO
	{
		
		private int _ID;
		
		private string _CUENTACATASTRAL;
		
		private string _REFERENCIAFOLIO;
		
		private string _DECLARACION;
		
		private string _FOLIOSIC;
		
		private string _NOMBRE;
		
		private string _CORREOELECTRONICO;
		
		private System.Nullable<System.DateTime> _FECHAALTA;
		
		private System.Nullable<System.DateTime> _FECHAEJERCIDO;
		
		private string _ESTADO;
		
		private string _OBSERVACIONES;
		
		private string _STATUSREGISTROTABLA;
		
		public FOLIOPAGOAVALUO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTACATASTRAL", DbType="NVarChar(17)")]
		public string CUENTACATASTRAL
		{
			get
			{
				return this._CUENTACATASTRAL;
			}
			set
			{
				if ((this._CUENTACATASTRAL != value))
				{
					this._CUENTACATASTRAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERENCIAFOLIO", DbType="VarChar(20)")]
		public string REFERENCIAFOLIO
		{
			get
			{
				return this._REFERENCIAFOLIO;
			}
			set
			{
				if ((this._REFERENCIAFOLIO != value))
				{
					this._REFERENCIAFOLIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DECLARACION", DbType="VarChar(7)")]
		public string DECLARACION
		{
			get
			{
				return this._DECLARACION;
			}
			set
			{
				if ((this._DECLARACION != value))
				{
					this._DECLARACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIOSIC", DbType="VarChar(255)")]
		public string FOLIOSIC
		{
			get
			{
				return this._FOLIOSIC;
			}
			set
			{
				if ((this._FOLIOSIC != value))
				{
					this._FOLIOSIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREOELECTRONICO", DbType="VarChar(255)")]
		public string CORREOELECTRONICO
		{
			get
			{
				return this._CORREOELECTRONICO;
			}
			set
			{
				if ((this._CORREOELECTRONICO != value))
				{
					this._CORREOELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAALTA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHAALTA
		{
			get
			{
				return this._FECHAALTA;
			}
			set
			{
				if ((this._FECHAALTA != value))
				{
					this._FECHAALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAEJERCIDO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHAEJERCIDO
		{
			get
			{
				return this._FECHAEJERCIDO;
			}
			set
			{
				if ((this._FECHAEJERCIDO != value))
				{
					this._FECHAEJERCIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(255)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(255)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="VarChar(255)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SeguimientoTramite")]
	public partial class SeguimientoTramite
	{
		
		private int _Id;
		
		private string _FK_NumeroTramite;
		
		private int _FK_Cat_TipoProcesoTramite;
		
		private int _FK_Cat_Coordinacion;
		
		private int _FK_Cat_EstatusTramite;
		
		private string _Tarea;
		
		private string _TipoFlujo;
		
		private string _Observaciones;
		
		private System.Nullable<int> _Duracion;
		
		private int _Orden;
		
		private System.Nullable<int> _FK_Cat_OpcionesSistema;
		
		public SeguimientoTramite()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_NumeroTramite", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FK_NumeroTramite
		{
			get
			{
				return this._FK_NumeroTramite;
			}
			set
			{
				if ((this._FK_NumeroTramite != value))
				{
					this._FK_NumeroTramite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_TipoProcesoTramite", DbType="Int NOT NULL")]
		public int FK_Cat_TipoProcesoTramite
		{
			get
			{
				return this._FK_Cat_TipoProcesoTramite;
			}
			set
			{
				if ((this._FK_Cat_TipoProcesoTramite != value))
				{
					this._FK_Cat_TipoProcesoTramite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_Coordinacion", DbType="Int NOT NULL")]
		public int FK_Cat_Coordinacion
		{
			get
			{
				return this._FK_Cat_Coordinacion;
			}
			set
			{
				if ((this._FK_Cat_Coordinacion != value))
				{
					this._FK_Cat_Coordinacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_EstatusTramite", DbType="Int NOT NULL")]
		public int FK_Cat_EstatusTramite
		{
			get
			{
				return this._FK_Cat_EstatusTramite;
			}
			set
			{
				if ((this._FK_Cat_EstatusTramite != value))
				{
					this._FK_Cat_EstatusTramite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarea", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Tarea
		{
			get
			{
				return this._Tarea;
			}
			set
			{
				if ((this._Tarea != value))
				{
					this._Tarea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoFlujo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoFlujo
		{
			get
			{
				return this._TipoFlujo;
			}
			set
			{
				if ((this._TipoFlujo != value))
				{
					this._TipoFlujo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="NVarChar(450)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this._Observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="Int")]
		public System.Nullable<int> Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this._Duracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int NOT NULL")]
		public int Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this._Orden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_OpcionesSistema", DbType="Int")]
		public System.Nullable<int> FK_Cat_OpcionesSistema
		{
			get
			{
				return this._FK_Cat_OpcionesSistema;
			}
			set
			{
				if ((this._FK_Cat_OpcionesSistema != value))
				{
					this._FK_Cat_OpcionesSistema = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIS_TRACAT_ABSTENCIONES")]
	public partial class SIS_TRACAT_ABSTENCIONES
	{
		
		private int _ID;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _USUARIOBAJA;
		
		private string _USUARIOALTA;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _OBS;
		
		private string _PISO;
		
		private string _OBS_ELIMINAR;
		
		public SIS_TRACAT_ABSTENCIONES()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(250)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(250)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(50)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NChar(17)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS", DbType="NVarChar(250)")]
		public string OBS
		{
			get
			{
				return this._OBS;
			}
			set
			{
				if ((this._OBS != value))
				{
					this._OBS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PISO", DbType="NVarChar(10)")]
		public string PISO
		{
			get
			{
				return this._PISO;
			}
			set
			{
				if ((this._PISO != value))
				{
					this._PISO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_ELIMINAR", DbType="NChar(250)")]
		public string OBS_ELIMINAR
		{
			get
			{
				return this._OBS_ELIMINAR;
			}
			set
			{
				if ((this._OBS_ELIMINAR != value))
				{
					this._OBS_ELIMINAR = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tramite")]
	public partial class Tramite
	{
		
		private int _Id;
		
		private string _ClaveCatastralOriginal;
		
		private string _ClaveCatastralEstandar;
		
		private System.DateTime _FechaInicial;
		
		private System.Nullable<System.DateTime> _FechaFinal;
		
		private int _FK_CatEstatus;
		
		private System.Nullable<bool> _Pagado;
		
		private System.Nullable<bool> _Condonado;
		
		private int _FK_Cat_Notaria;
		
		private string _Prioridad;
		
		private string _Observaciones;
		
		private int _FK_Cat_TipodeProcesoTramite;
		
		private string _FK_NombreUsuario;
		
		private System.Nullable<int> _Region;
		
		private System.Nullable<int> _Manzana;
		
		private System.Nullable<int> _Lote;
		
		private System.Nullable<int> _Departamento;
		
		private int _FK_Cat_TipodePredio;
		
		private System.Nullable<int> _NumeroCuenta;
		
		private int _Delegacion;
		
		private string _NumeroTramite;
		
		private int _FK_Cat_Solicitante;
		
		private string _NombrePersonalSolicitante;
		
		private string _ObservacionAclaracion;
		
		private System.Nullable<bool> _Procede;
		
		private string _Entidad;
		
		private string _Tipo;
		
		private string _Año;
		
		private string _Consecutivo;
		
		private string _Derivada;
		
		private string _TipoBusqueda;
		
		private System.Nullable<bool> _Bloqueado;
		
		private System.Nullable<bool> _Reserva;
		
		private System.Nullable<bool> _Rechazado;
		
		private System.Nullable<int> _NumeroClave;
		
		private System.Nullable<int> _NumeroCuentas;
		
		private System.Nullable<bool> _Excentopago;
		
		private string _FK_Cat_TipoClaveCatastralGenerada;
		
		private string _FK_Cat_TipoInspeccion;
		
		private System.Nullable<bool> _PagarReingreso;
		
		private string _NumeroTramiteSIC;
		
		private string _NumeroTramiteValuacion;
		
		private System.Nullable<bool> _ProntoPago;
		
		private string _Sector;
		
		private string _Localidad;
		
		private string _Predio;
		
		private string _Edificio;
		
		private string _Unidad;
		
		private string _Zona;
		
		private System.Nullable<int> _FK_Cat_Municipio;
		
		private bool _RequiereCartografia;
		
		private System.Nullable<int> _ObjectId_Cartografico;
		
		private string _Condominio;
		
		private string _OtroEstado;
		
		private string _Folio;
		
		private string _Corett;
		
		private System.Nullable<int> _FK_Cat_Dependencia;
		
		private System.Nullable<bool> _Habilitado;
		
		private System.Nullable<double> _SuperficieConstruccion;
		
		private System.Nullable<double> _SuperficieTerreno;
		
		private string _usuarioSolicitante;
		
		private string _Observaciones_Rechazo_Direccion;
		
		private string _FK_CatCoordinacion;
		
		private string _USUARIOCANCELA;
		
		public Tramite()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveCatastralOriginal", DbType="NVarChar(17)")]
		public string ClaveCatastralOriginal
		{
			get
			{
				return this._ClaveCatastralOriginal;
			}
			set
			{
				if ((this._ClaveCatastralOriginal != value))
				{
					this._ClaveCatastralOriginal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveCatastralEstandar", DbType="NVarChar(31)")]
		public string ClaveCatastralEstandar
		{
			get
			{
				return this._ClaveCatastralEstandar;
			}
			set
			{
				if ((this._ClaveCatastralEstandar != value))
				{
					this._ClaveCatastralEstandar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicial", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicial
		{
			get
			{
				return this._FechaInicial;
			}
			set
			{
				if ((this._FechaInicial != value))
				{
					this._FechaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinal", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFinal
		{
			get
			{
				return this._FechaFinal;
			}
			set
			{
				if ((this._FechaFinal != value))
				{
					this._FechaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_CatEstatus", DbType="Int NOT NULL")]
		public int FK_CatEstatus
		{
			get
			{
				return this._FK_CatEstatus;
			}
			set
			{
				if ((this._FK_CatEstatus != value))
				{
					this._FK_CatEstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pagado", DbType="Bit")]
		public System.Nullable<bool> Pagado
		{
			get
			{
				return this._Pagado;
			}
			set
			{
				if ((this._Pagado != value))
				{
					this._Pagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condonado", DbType="Bit")]
		public System.Nullable<bool> Condonado
		{
			get
			{
				return this._Condonado;
			}
			set
			{
				if ((this._Condonado != value))
				{
					this._Condonado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_Notaria", DbType="Int NOT NULL")]
		public int FK_Cat_Notaria
		{
			get
			{
				return this._FK_Cat_Notaria;
			}
			set
			{
				if ((this._FK_Cat_Notaria != value))
				{
					this._FK_Cat_Notaria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prioridad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prioridad
		{
			get
			{
				return this._Prioridad;
			}
			set
			{
				if ((this._Prioridad != value))
				{
					this._Prioridad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="NVarChar(500)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this._Observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_TipodeProcesoTramite", DbType="Int NOT NULL")]
		public int FK_Cat_TipodeProcesoTramite
		{
			get
			{
				return this._FK_Cat_TipodeProcesoTramite;
			}
			set
			{
				if ((this._FK_Cat_TipodeProcesoTramite != value))
				{
					this._FK_Cat_TipodeProcesoTramite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_NombreUsuario", DbType="NVarChar(120) NOT NULL", CanBeNull=false)]
		public string FK_NombreUsuario
		{
			get
			{
				return this._FK_NombreUsuario;
			}
			set
			{
				if ((this._FK_NombreUsuario != value))
				{
					this._FK_NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="Int")]
		public System.Nullable<int> Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manzana", DbType="Int")]
		public System.Nullable<int> Manzana
		{
			get
			{
				return this._Manzana;
			}
			set
			{
				if ((this._Manzana != value))
				{
					this._Manzana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lote", DbType="Int")]
		public System.Nullable<int> Lote
		{
			get
			{
				return this._Lote;
			}
			set
			{
				if ((this._Lote != value))
				{
					this._Lote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="Int")]
		public System.Nullable<int> Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_TipodePredio", DbType="Int NOT NULL")]
		public int FK_Cat_TipodePredio
		{
			get
			{
				return this._FK_Cat_TipodePredio;
			}
			set
			{
				if ((this._FK_Cat_TipodePredio != value))
				{
					this._FK_Cat_TipodePredio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCuenta", DbType="Int")]
		public System.Nullable<int> NumeroCuenta
		{
			get
			{
				return this._NumeroCuenta;
			}
			set
			{
				if ((this._NumeroCuenta != value))
				{
					this._NumeroCuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delegacion", DbType="Int NOT NULL")]
		public int Delegacion
		{
			get
			{
				return this._Delegacion;
			}
			set
			{
				if ((this._Delegacion != value))
				{
					this._Delegacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTramite", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NumeroTramite
		{
			get
			{
				return this._NumeroTramite;
			}
			set
			{
				if ((this._NumeroTramite != value))
				{
					this._NumeroTramite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_Solicitante", DbType="Int NOT NULL")]
		public int FK_Cat_Solicitante
		{
			get
			{
				return this._FK_Cat_Solicitante;
			}
			set
			{
				if ((this._FK_Cat_Solicitante != value))
				{
					this._FK_Cat_Solicitante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePersonalSolicitante", DbType="NVarChar(150)")]
		public string NombrePersonalSolicitante
		{
			get
			{
				return this._NombrePersonalSolicitante;
			}
			set
			{
				if ((this._NombrePersonalSolicitante != value))
				{
					this._NombrePersonalSolicitante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObservacionAclaracion", DbType="NVarChar(400)")]
		public string ObservacionAclaracion
		{
			get
			{
				return this._ObservacionAclaracion;
			}
			set
			{
				if ((this._ObservacionAclaracion != value))
				{
					this._ObservacionAclaracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Procede", DbType="Bit")]
		public System.Nullable<bool> Procede
		{
			get
			{
				return this._Procede;
			}
			set
			{
				if ((this._Procede != value))
				{
					this._Procede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entidad", DbType="NVarChar(50)")]
		public string Entidad
		{
			get
			{
				return this._Entidad;
			}
			set
			{
				if ((this._Entidad != value))
				{
					this._Entidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Año", DbType="NVarChar(50)")]
		public string Año
		{
			get
			{
				return this._Año;
			}
			set
			{
				if ((this._Año != value))
				{
					this._Año = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Consecutivo", DbType="NVarChar(50)")]
		public string Consecutivo
		{
			get
			{
				return this._Consecutivo;
			}
			set
			{
				if ((this._Consecutivo != value))
				{
					this._Consecutivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Derivada", DbType="NVarChar(50)")]
		public string Derivada
		{
			get
			{
				return this._Derivada;
			}
			set
			{
				if ((this._Derivada != value))
				{
					this._Derivada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoBusqueda", DbType="NVarChar(50)")]
		public string TipoBusqueda
		{
			get
			{
				return this._TipoBusqueda;
			}
			set
			{
				if ((this._TipoBusqueda != value))
				{
					this._TipoBusqueda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloqueado", DbType="Bit")]
		public System.Nullable<bool> Bloqueado
		{
			get
			{
				return this._Bloqueado;
			}
			set
			{
				if ((this._Bloqueado != value))
				{
					this._Bloqueado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserva", DbType="Bit")]
		public System.Nullable<bool> Reserva
		{
			get
			{
				return this._Reserva;
			}
			set
			{
				if ((this._Reserva != value))
				{
					this._Reserva = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rechazado", DbType="Bit")]
		public System.Nullable<bool> Rechazado
		{
			get
			{
				return this._Rechazado;
			}
			set
			{
				if ((this._Rechazado != value))
				{
					this._Rechazado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroClave", DbType="Int")]
		public System.Nullable<int> NumeroClave
		{
			get
			{
				return this._NumeroClave;
			}
			set
			{
				if ((this._NumeroClave != value))
				{
					this._NumeroClave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCuentas", DbType="Int")]
		public System.Nullable<int> NumeroCuentas
		{
			get
			{
				return this._NumeroCuentas;
			}
			set
			{
				if ((this._NumeroCuentas != value))
				{
					this._NumeroCuentas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Excentopago", DbType="Bit")]
		public System.Nullable<bool> Excentopago
		{
			get
			{
				return this._Excentopago;
			}
			set
			{
				if ((this._Excentopago != value))
				{
					this._Excentopago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_TipoClaveCatastralGenerada", DbType="VarChar(120)")]
		public string FK_Cat_TipoClaveCatastralGenerada
		{
			get
			{
				return this._FK_Cat_TipoClaveCatastralGenerada;
			}
			set
			{
				if ((this._FK_Cat_TipoClaveCatastralGenerada != value))
				{
					this._FK_Cat_TipoClaveCatastralGenerada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_TipoInspeccion", DbType="VarChar(120)")]
		public string FK_Cat_TipoInspeccion
		{
			get
			{
				return this._FK_Cat_TipoInspeccion;
			}
			set
			{
				if ((this._FK_Cat_TipoInspeccion != value))
				{
					this._FK_Cat_TipoInspeccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagarReingreso", DbType="Bit")]
		public System.Nullable<bool> PagarReingreso
		{
			get
			{
				return this._PagarReingreso;
			}
			set
			{
				if ((this._PagarReingreso != value))
				{
					this._PagarReingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTramiteSIC", DbType="VarChar(20)")]
		public string NumeroTramiteSIC
		{
			get
			{
				return this._NumeroTramiteSIC;
			}
			set
			{
				if ((this._NumeroTramiteSIC != value))
				{
					this._NumeroTramiteSIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTramiteValuacion", DbType="VarChar(20)")]
		public string NumeroTramiteValuacion
		{
			get
			{
				return this._NumeroTramiteValuacion;
			}
			set
			{
				if ((this._NumeroTramiteValuacion != value))
				{
					this._NumeroTramiteValuacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProntoPago", DbType="Bit")]
		public System.Nullable<bool> ProntoPago
		{
			get
			{
				return this._ProntoPago;
			}
			set
			{
				if ((this._ProntoPago != value))
				{
					this._ProntoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="VarChar(3)")]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this._Sector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidad", DbType="NVarChar(4)")]
		public string Localidad
		{
			get
			{
				return this._Localidad;
			}
			set
			{
				if ((this._Localidad != value))
				{
					this._Localidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Predio", DbType="NVarChar(5)")]
		public string Predio
		{
			get
			{
				return this._Predio;
			}
			set
			{
				if ((this._Predio != value))
				{
					this._Predio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edificio", DbType="NVarChar(2)")]
		public string Edificio
		{
			get
			{
				return this._Edificio;
			}
			set
			{
				if ((this._Edificio != value))
				{
					this._Edificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidad", DbType="NVarChar(4)")]
		public string Unidad
		{
			get
			{
				return this._Unidad;
			}
			set
			{
				if ((this._Unidad != value))
				{
					this._Unidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="NVarChar(2)")]
		public string Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this._Zona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_Municipio", DbType="Int")]
		public System.Nullable<int> FK_Cat_Municipio
		{
			get
			{
				return this._FK_Cat_Municipio;
			}
			set
			{
				if ((this._FK_Cat_Municipio != value))
				{
					this._FK_Cat_Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiereCartografia", DbType="Bit NOT NULL")]
		public bool RequiereCartografia
		{
			get
			{
				return this._RequiereCartografia;
			}
			set
			{
				if ((this._RequiereCartografia != value))
				{
					this._RequiereCartografia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectId_Cartografico", DbType="Int")]
		public System.Nullable<int> ObjectId_Cartografico
		{
			get
			{
				return this._ObjectId_Cartografico;
			}
			set
			{
				if ((this._ObjectId_Cartografico != value))
				{
					this._ObjectId_Cartografico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condominio", DbType="NVarChar(4)")]
		public string Condominio
		{
			get
			{
				return this._Condominio;
			}
			set
			{
				if ((this._Condominio != value))
				{
					this._Condominio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtroEstado", DbType="NVarChar(300)")]
		public string OtroEstado
		{
			get
			{
				return this._OtroEstado;
			}
			set
			{
				if ((this._OtroEstado != value))
				{
					this._OtroEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="NVarChar(250)")]
		public string Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this._Folio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corett", DbType="NVarChar(250)")]
		public string Corett
		{
			get
			{
				return this._Corett;
			}
			set
			{
				if ((this._Corett != value))
				{
					this._Corett = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Cat_Dependencia", DbType="Int")]
		public System.Nullable<int> FK_Cat_Dependencia
		{
			get
			{
				return this._FK_Cat_Dependencia;
			}
			set
			{
				if ((this._FK_Cat_Dependencia != value))
				{
					this._FK_Cat_Dependencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habilitado", DbType="Bit")]
		public System.Nullable<bool> Habilitado
		{
			get
			{
				return this._Habilitado;
			}
			set
			{
				if ((this._Habilitado != value))
				{
					this._Habilitado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperficieConstruccion", DbType="Float")]
		public System.Nullable<double> SuperficieConstruccion
		{
			get
			{
				return this._SuperficieConstruccion;
			}
			set
			{
				if ((this._SuperficieConstruccion != value))
				{
					this._SuperficieConstruccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuperficieTerreno", DbType="Float")]
		public System.Nullable<double> SuperficieTerreno
		{
			get
			{
				return this._SuperficieTerreno;
			}
			set
			{
				if ((this._SuperficieTerreno != value))
				{
					this._SuperficieTerreno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioSolicitante", DbType="NVarChar(150)")]
		public string usuarioSolicitante
		{
			get
			{
				return this._usuarioSolicitante;
			}
			set
			{
				if ((this._usuarioSolicitante != value))
				{
					this._usuarioSolicitante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones_Rechazo_Direccion", DbType="NVarChar(255)")]
		public string Observaciones_Rechazo_Direccion
		{
			get
			{
				return this._Observaciones_Rechazo_Direccion;
			}
			set
			{
				if ((this._Observaciones_Rechazo_Direccion != value))
				{
					this._Observaciones_Rechazo_Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_CatCoordinacion", DbType="NVarChar(10)")]
		public string FK_CatCoordinacion
		{
			get
			{
				return this._FK_CatCoordinacion;
			}
			set
			{
				if ((this._FK_CatCoordinacion != value))
				{
					this._FK_CatCoordinacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOCANCELA", DbType="NVarChar(250)")]
		public string USUARIOCANCELA
		{
			get
			{
				return this._USUARIOCANCELA;
			}
			set
			{
				if ((this._USUARIOCANCELA != value))
				{
					this._USUARIOCANCELA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIS_TRACAT_MC")]
	public partial class SIS_TRACAT_MC
	{
		
		private int _OBJECTID;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _FOLIO_TRAMITE;
		
		private string _TIPO_TRAMITE;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _CVE_PREDIAL;
		
		private string _OBSERVACIONES;
		
		private string _TRAMITADOR;
		
		private System.Nullable<bool> _EN_USO;
		
		private System.Data.Linq.Binary _IMAGEN;
		
		private string _SOLICITANTE;
		
		private string _PROPIETARIO;
		
		private string _UBICACION;
		
		private string _NOTIFICACION;
		
		private bool _NOTIFICACION_RECHAZO;
		
		private System.Nullable<bool> _AVALUO;
		
		private string _FOLIO_PAGO_AVALUO;
		
		private System.Nullable<bool> _IGUAL_CARTOGRAFIA;
		
		private string _CORREOELECTRONICO;
		
		private System.Nullable<int> _CONTROLFOLIO;
		
		private string _PROPIETARIO_CURP;
		
		private string _PROPIETARIO_RFC;
		
		private string _PROPIETARIO_TELEFONO;
		
		private string _PROPIETARIO_DOMICILIO_CALLE;
		
		private string _PROPIETARIO_DOMICILIO_NO_EXT;
		
		private string _PROPIETARIO_DOMICILIO_COLONIA;
		
		private string _PROPIETARIO_DOMICILIO_CP;
		
		private string _PROPIETARIO_DOMICILIO_LOCALIDAD;
		
		private string _PROPIETARIO_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_DOMICILIO_CALLE;
		
		private string _INMUEBLE_DOMICILIO_NO_EXT;
		
		private string _INMUEBLE_DOMICILIO_COLONIA;
		
		private string _INMUEBLE_DOMICILIO_CP;
		
		private string _INMUEBLE_DOMICILIO_LOCALIDAD;
		
		private string _INMUEBLE_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_TIPO_PREDIO;
		
		private System.Nullable<decimal> _INMUEBLE_SUPERFICIE_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_CONCRETO_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TEJABAN_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TOTAL_M2;
		
		private string _INMUEBLE_AVANCE_OBRA;
		
		private string _INMUEBLE_ESTADO_CONSERVACION;
		
		private System.Nullable<int> _INMUEBLE_ANTIGUEDAD_ANIOS;
		
		private string _INMUEBLE_TIPO_USO;
		
		private string _INMUEBLE_TIPO_INDUSTRIAL;
		
		private string _INMUEBLE_COMERCIAL_Y_SERVICIO;
		
		public SIS_TRACAT_MC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(200)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(200)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_TRAMITE", DbType="NVarChar(30)")]
		public string FOLIO_TRAMITE
		{
			get
			{
				return this._FOLIO_TRAMITE;
			}
			set
			{
				if ((this._FOLIO_TRAMITE != value))
				{
					this._FOLIO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_TRAMITE", DbType="NVarChar(200)")]
		public string TIPO_TRAMITE
		{
			get
			{
				return this._TIPO_TRAMITE;
			}
			set
			{
				if ((this._TIPO_TRAMITE != value))
				{
					this._TIPO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(31)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_PREDIAL", DbType="NVarChar(30)")]
		public string CVE_PREDIAL
		{
			get
			{
				return this._CVE_PREDIAL;
			}
			set
			{
				if ((this._CVE_PREDIAL != value))
				{
					this._CVE_PREDIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="NVarChar(MAX)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAMITADOR", DbType="NVarChar(200)")]
		public string TRAMITADOR
		{
			get
			{
				return this._TRAMITADOR;
			}
			set
			{
				if ((this._TRAMITADOR != value))
				{
					this._TRAMITADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_USO", DbType="Bit")]
		public System.Nullable<bool> EN_USO
		{
			get
			{
				return this._EN_USO;
			}
			set
			{
				if ((this._EN_USO != value))
				{
					this._EN_USO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary IMAGEN
		{
			get
			{
				return this._IMAGEN;
			}
			set
			{
				if ((this._IMAGEN != value))
				{
					this._IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITANTE", DbType="NVarChar(255)")]
		public string SOLICITANTE
		{
			get
			{
				return this._SOLICITANTE;
			}
			set
			{
				if ((this._SOLICITANTE != value))
				{
					this._SOLICITANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO", DbType="VarChar(200)")]
		public string PROPIETARIO
		{
			get
			{
				return this._PROPIETARIO;
			}
			set
			{
				if ((this._PROPIETARIO != value))
				{
					this._PROPIETARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION", DbType="NVarChar(MAX)")]
		public string UBICACION
		{
			get
			{
				return this._UBICACION;
			}
			set
			{
				if ((this._UBICACION != value))
				{
					this._UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFICACION", DbType="VarChar(250)")]
		public string NOTIFICACION
		{
			get
			{
				return this._NOTIFICACION;
			}
			set
			{
				if ((this._NOTIFICACION != value))
				{
					this._NOTIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFICACION_RECHAZO", DbType="Bit NOT NULL")]
		public bool NOTIFICACION_RECHAZO
		{
			get
			{
				return this._NOTIFICACION_RECHAZO;
			}
			set
			{
				if ((this._NOTIFICACION_RECHAZO != value))
				{
					this._NOTIFICACION_RECHAZO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVALUO", DbType="Bit")]
		public System.Nullable<bool> AVALUO
		{
			get
			{
				return this._AVALUO;
			}
			set
			{
				if ((this._AVALUO != value))
				{
					this._AVALUO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_PAGO_AVALUO", DbType="VarChar(50)")]
		public string FOLIO_PAGO_AVALUO
		{
			get
			{
				return this._FOLIO_PAGO_AVALUO;
			}
			set
			{
				if ((this._FOLIO_PAGO_AVALUO != value))
				{
					this._FOLIO_PAGO_AVALUO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGUAL_CARTOGRAFIA", DbType="Bit")]
		public System.Nullable<bool> IGUAL_CARTOGRAFIA
		{
			get
			{
				return this._IGUAL_CARTOGRAFIA;
			}
			set
			{
				if ((this._IGUAL_CARTOGRAFIA != value))
				{
					this._IGUAL_CARTOGRAFIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREOELECTRONICO", DbType="VarChar(255)")]
		public string CORREOELECTRONICO
		{
			get
			{
				return this._CORREOELECTRONICO;
			}
			set
			{
				if ((this._CORREOELECTRONICO != value))
				{
					this._CORREOELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLFOLIO", DbType="Int")]
		public System.Nullable<int> CONTROLFOLIO
		{
			get
			{
				return this._CONTROLFOLIO;
			}
			set
			{
				if ((this._CONTROLFOLIO != value))
				{
					this._CONTROLFOLIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_CURP", DbType="NVarChar(255)")]
		public string PROPIETARIO_CURP
		{
			get
			{
				return this._PROPIETARIO_CURP;
			}
			set
			{
				if ((this._PROPIETARIO_CURP != value))
				{
					this._PROPIETARIO_CURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_RFC", DbType="NVarChar(255)")]
		public string PROPIETARIO_RFC
		{
			get
			{
				return this._PROPIETARIO_RFC;
			}
			set
			{
				if ((this._PROPIETARIO_RFC != value))
				{
					this._PROPIETARIO_RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_TELEFONO", DbType="NVarChar(20)")]
		public string PROPIETARIO_TELEFONO
		{
			get
			{
				return this._PROPIETARIO_TELEFONO;
			}
			set
			{
				if ((this._PROPIETARIO_TELEFONO != value))
				{
					this._PROPIETARIO_TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_CALLE
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CALLE != value))
				{
					this._PROPIETARIO_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_NO_EXT
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_NO_EXT != value))
				{
					this._PROPIETARIO_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_COLONIA
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_COLONIA != value))
				{
					this._PROPIETARIO_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_CP
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CP;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CP != value))
				{
					this._PROPIETARIO_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_LOCALIDAD != value))
				{
					this._PROPIETARIO_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_MUNICIPIO != value))
				{
					this._PROPIETARIO_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_CALLE
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CALLE != value))
				{
					this._INMUEBLE_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_NO_EXT
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_NO_EXT != value))
				{
					this._INMUEBLE_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_COLONIA
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_COLONIA != value))
				{
					this._INMUEBLE_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_CP
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CP;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CP != value))
				{
					this._INMUEBLE_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_LOCALIDAD != value))
				{
					this._INMUEBLE_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_MUNICIPIO != value))
				{
					this._INMUEBLE_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_PREDIO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_PREDIO
		{
			get
			{
				return this._INMUEBLE_TIPO_PREDIO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_PREDIO != value))
				{
					this._INMUEBLE_TIPO_PREDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_SUPERFICIE_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_SUPERFICIE_M2
		{
			get
			{
				return this._INMUEBLE_SUPERFICIE_M2;
			}
			set
			{
				if ((this._INMUEBLE_SUPERFICIE_M2 != value))
				{
					this._INMUEBLE_SUPERFICIE_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_CONCRETO_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_CONCRETO_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_CONCRETO_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TEJABAN_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TEJABAN_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TEJABAN_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TOTAL_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TOTAL_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TOTAL_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TOTAL_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TOTAL_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_AVANCE_OBRA", DbType="NVarChar(50)")]
		public string INMUEBLE_AVANCE_OBRA
		{
			get
			{
				return this._INMUEBLE_AVANCE_OBRA;
			}
			set
			{
				if ((this._INMUEBLE_AVANCE_OBRA != value))
				{
					this._INMUEBLE_AVANCE_OBRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ESTADO_CONSERVACION", DbType="NVarChar(50)")]
		public string INMUEBLE_ESTADO_CONSERVACION
		{
			get
			{
				return this._INMUEBLE_ESTADO_CONSERVACION;
			}
			set
			{
				if ((this._INMUEBLE_ESTADO_CONSERVACION != value))
				{
					this._INMUEBLE_ESTADO_CONSERVACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ANTIGUEDAD_ANIOS", DbType="Int")]
		public System.Nullable<int> INMUEBLE_ANTIGUEDAD_ANIOS
		{
			get
			{
				return this._INMUEBLE_ANTIGUEDAD_ANIOS;
			}
			set
			{
				if ((this._INMUEBLE_ANTIGUEDAD_ANIOS != value))
				{
					this._INMUEBLE_ANTIGUEDAD_ANIOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_USO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_USO
		{
			get
			{
				return this._INMUEBLE_TIPO_USO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_USO != value))
				{
					this._INMUEBLE_TIPO_USO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_INDUSTRIAL", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_INDUSTRIAL
		{
			get
			{
				return this._INMUEBLE_TIPO_INDUSTRIAL;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_INDUSTRIAL != value))
				{
					this._INMUEBLE_TIPO_INDUSTRIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_COMERCIAL_Y_SERVICIO", DbType="NVarChar(50)")]
		public string INMUEBLE_COMERCIAL_Y_SERVICIO
		{
			get
			{
				return this._INMUEBLE_COMERCIAL_Y_SERVICIO;
			}
			set
			{
				if ((this._INMUEBLE_COMERCIAL_Y_SERVICIO != value))
				{
					this._INMUEBLE_COMERCIAL_Y_SERVICIO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIS_TRACAT_AC")]
	public partial class SIS_TRACAT_AC
	{
		
		private int _OBJECTID;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _TIPO_TRAMITE;
		
		private string _FOLIO_TRAMITE;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _OBSERVACIONES;
		
		private string _TRAMITADOR;
		
		private string _SOLICITANTE;
		
		private string _UBICACION;
		
		private string _FOLIO_MC;
		
		private string _FOLIO_PAGO_AVALUO;
		
		private string _NO_NOTARIA;
		
		private string _NO_ESCRITURA;
		
		private string _NATURALEZA_DEL_ACTO;
		
		private System.Nullable<bool> _BANDERA_EXTERNO;
		
		private System.Nullable<bool> _BANDERA_ACEPTADO;
		
		private System.Nullable<bool> _BANDERA_TD;
		
		private string _CORREOELECTRONICO;
		
		private System.Nullable<int> _CONTROLFOLIO;
		
		private string _PROPIETARIO_CURP;
		
		private string _PROPIETARIO_RFC;
		
		private string _PROPIETARIO_TELEFONO;
		
		private string _PROPIETARIO_DOMICILIO_CALLE;
		
		private string _PROPIETARIO_DOMICILIO_NO_EXT;
		
		private string _PROPIETARIO_DOMICILIO_COLONIA;
		
		private string _PROPIETARIO_DOMICILIO_CP;
		
		private string _PROPIETARIO_DOMICILIO_LOCALIDAD;
		
		private string _PROPIETARIO_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_DOMICILIO_CALLE;
		
		private string _INMUEBLE_DOMICILIO_NO_EXT;
		
		private string _INMUEBLE_DOMICILIO_COLONIA;
		
		private string _INMUEBLE_DOMICILIO_CP;
		
		private string _INMUEBLE_DOMICILIO_LOCALIDAD;
		
		private string _INMUEBLE_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_TIPO_PREDIO;
		
		private System.Nullable<decimal> _INMUEBLE_SUPERFICIE_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_CONCRETO_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TEJABAN_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TOTAL_M2;
		
		private string _INMUEBLE_AVANCE_OBRA;
		
		private string _INMUEBLE_ESTADO_CONSERVACION;
		
		private System.Nullable<int> _INMUEBLE_ANTIGUEDAD_ANIOS;
		
		private string _INMUEBLE_TIPO_USO;
		
		private string _INMUEBLE_TIPO_INDUSTRIAL;
		
		private string _INMUEBLE_COMERCIAL_Y_SERVICIO;
		
		public SIS_TRACAT_AC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="VarChar(200)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="VarChar(200)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_TRAMITE", DbType="VarChar(50)")]
		public string TIPO_TRAMITE
		{
			get
			{
				return this._TIPO_TRAMITE;
			}
			set
			{
				if ((this._TIPO_TRAMITE != value))
				{
					this._TIPO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_TRAMITE", DbType="VarChar(50)")]
		public string FOLIO_TRAMITE
		{
			get
			{
				return this._FOLIO_TRAMITE;
			}
			set
			{
				if ((this._FOLIO_TRAMITE != value))
				{
					this._FOLIO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="VarChar(50)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="VarChar(50)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(255)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAMITADOR", DbType="VarChar(200)")]
		public string TRAMITADOR
		{
			get
			{
				return this._TRAMITADOR;
			}
			set
			{
				if ((this._TRAMITADOR != value))
				{
					this._TRAMITADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITANTE", DbType="VarChar(200)")]
		public string SOLICITANTE
		{
			get
			{
				return this._SOLICITANTE;
			}
			set
			{
				if ((this._SOLICITANTE != value))
				{
					this._SOLICITANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string UBICACION
		{
			get
			{
				return this._UBICACION;
			}
			set
			{
				if ((this._UBICACION != value))
				{
					this._UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_MC", DbType="VarChar(50)")]
		public string FOLIO_MC
		{
			get
			{
				return this._FOLIO_MC;
			}
			set
			{
				if ((this._FOLIO_MC != value))
				{
					this._FOLIO_MC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_PAGO_AVALUO", DbType="VarChar(50)")]
		public string FOLIO_PAGO_AVALUO
		{
			get
			{
				return this._FOLIO_PAGO_AVALUO;
			}
			set
			{
				if ((this._FOLIO_PAGO_AVALUO != value))
				{
					this._FOLIO_PAGO_AVALUO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_NOTARIA", DbType="NVarChar(5)")]
		public string NO_NOTARIA
		{
			get
			{
				return this._NO_NOTARIA;
			}
			set
			{
				if ((this._NO_NOTARIA != value))
				{
					this._NO_NOTARIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_ESCRITURA", DbType="NVarChar(50)")]
		public string NO_ESCRITURA
		{
			get
			{
				return this._NO_ESCRITURA;
			}
			set
			{
				if ((this._NO_ESCRITURA != value))
				{
					this._NO_ESCRITURA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATURALEZA_DEL_ACTO", DbType="NVarChar(250)")]
		public string NATURALEZA_DEL_ACTO
		{
			get
			{
				return this._NATURALEZA_DEL_ACTO;
			}
			set
			{
				if ((this._NATURALEZA_DEL_ACTO != value))
				{
					this._NATURALEZA_DEL_ACTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANDERA_EXTERNO", DbType="Bit")]
		public System.Nullable<bool> BANDERA_EXTERNO
		{
			get
			{
				return this._BANDERA_EXTERNO;
			}
			set
			{
				if ((this._BANDERA_EXTERNO != value))
				{
					this._BANDERA_EXTERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANDERA_ACEPTADO", DbType="Bit")]
		public System.Nullable<bool> BANDERA_ACEPTADO
		{
			get
			{
				return this._BANDERA_ACEPTADO;
			}
			set
			{
				if ((this._BANDERA_ACEPTADO != value))
				{
					this._BANDERA_ACEPTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANDERA_TD", DbType="Bit")]
		public System.Nullable<bool> BANDERA_TD
		{
			get
			{
				return this._BANDERA_TD;
			}
			set
			{
				if ((this._BANDERA_TD != value))
				{
					this._BANDERA_TD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREOELECTRONICO", DbType="VarChar(255)")]
		public string CORREOELECTRONICO
		{
			get
			{
				return this._CORREOELECTRONICO;
			}
			set
			{
				if ((this._CORREOELECTRONICO != value))
				{
					this._CORREOELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLFOLIO", DbType="Int")]
		public System.Nullable<int> CONTROLFOLIO
		{
			get
			{
				return this._CONTROLFOLIO;
			}
			set
			{
				if ((this._CONTROLFOLIO != value))
				{
					this._CONTROLFOLIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_CURP", DbType="NVarChar(255)")]
		public string PROPIETARIO_CURP
		{
			get
			{
				return this._PROPIETARIO_CURP;
			}
			set
			{
				if ((this._PROPIETARIO_CURP != value))
				{
					this._PROPIETARIO_CURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_RFC", DbType="NVarChar(255)")]
		public string PROPIETARIO_RFC
		{
			get
			{
				return this._PROPIETARIO_RFC;
			}
			set
			{
				if ((this._PROPIETARIO_RFC != value))
				{
					this._PROPIETARIO_RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_TELEFONO", DbType="NVarChar(20)")]
		public string PROPIETARIO_TELEFONO
		{
			get
			{
				return this._PROPIETARIO_TELEFONO;
			}
			set
			{
				if ((this._PROPIETARIO_TELEFONO != value))
				{
					this._PROPIETARIO_TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_CALLE
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CALLE != value))
				{
					this._PROPIETARIO_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_NO_EXT
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_NO_EXT != value))
				{
					this._PROPIETARIO_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_COLONIA
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_COLONIA != value))
				{
					this._PROPIETARIO_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_CP
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CP;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CP != value))
				{
					this._PROPIETARIO_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_LOCALIDAD != value))
				{
					this._PROPIETARIO_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_MUNICIPIO != value))
				{
					this._PROPIETARIO_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_CALLE
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CALLE != value))
				{
					this._INMUEBLE_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_NO_EXT
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_NO_EXT != value))
				{
					this._INMUEBLE_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_COLONIA
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_COLONIA != value))
				{
					this._INMUEBLE_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_CP
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CP;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CP != value))
				{
					this._INMUEBLE_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_LOCALIDAD != value))
				{
					this._INMUEBLE_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_MUNICIPIO != value))
				{
					this._INMUEBLE_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_PREDIO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_PREDIO
		{
			get
			{
				return this._INMUEBLE_TIPO_PREDIO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_PREDIO != value))
				{
					this._INMUEBLE_TIPO_PREDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_SUPERFICIE_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_SUPERFICIE_M2
		{
			get
			{
				return this._INMUEBLE_SUPERFICIE_M2;
			}
			set
			{
				if ((this._INMUEBLE_SUPERFICIE_M2 != value))
				{
					this._INMUEBLE_SUPERFICIE_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_CONCRETO_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_CONCRETO_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_CONCRETO_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TEJABAN_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TEJABAN_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TEJABAN_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TOTAL_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TOTAL_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TOTAL_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TOTAL_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TOTAL_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_AVANCE_OBRA", DbType="NVarChar(50)")]
		public string INMUEBLE_AVANCE_OBRA
		{
			get
			{
				return this._INMUEBLE_AVANCE_OBRA;
			}
			set
			{
				if ((this._INMUEBLE_AVANCE_OBRA != value))
				{
					this._INMUEBLE_AVANCE_OBRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ESTADO_CONSERVACION", DbType="NVarChar(50)")]
		public string INMUEBLE_ESTADO_CONSERVACION
		{
			get
			{
				return this._INMUEBLE_ESTADO_CONSERVACION;
			}
			set
			{
				if ((this._INMUEBLE_ESTADO_CONSERVACION != value))
				{
					this._INMUEBLE_ESTADO_CONSERVACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ANTIGUEDAD_ANIOS", DbType="Int")]
		public System.Nullable<int> INMUEBLE_ANTIGUEDAD_ANIOS
		{
			get
			{
				return this._INMUEBLE_ANTIGUEDAD_ANIOS;
			}
			set
			{
				if ((this._INMUEBLE_ANTIGUEDAD_ANIOS != value))
				{
					this._INMUEBLE_ANTIGUEDAD_ANIOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_USO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_USO
		{
			get
			{
				return this._INMUEBLE_TIPO_USO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_USO != value))
				{
					this._INMUEBLE_TIPO_USO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_INDUSTRIAL", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_INDUSTRIAL
		{
			get
			{
				return this._INMUEBLE_TIPO_INDUSTRIAL;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_INDUSTRIAL != value))
				{
					this._INMUEBLE_TIPO_INDUSTRIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_COMERCIAL_Y_SERVICIO", DbType="NVarChar(50)")]
		public string INMUEBLE_COMERCIAL_Y_SERVICIO
		{
			get
			{
				return this._INMUEBLE_COMERCIAL_Y_SERVICIO;
			}
			set
			{
				if ((this._INMUEBLE_COMERCIAL_Y_SERVICIO != value))
				{
					this._INMUEBLE_COMERCIAL_Y_SERVICIO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIS_TRACAT_SOLICITUD_MC_AV")]
	public partial class SIS_TRACAT_SOLICITUD_MC_AV
	{
		
		private int _OBJECTID;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _FOLIO_TRAMITE;
		
		private string _TIPO_TRAMITE;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _CVE_PREDIAL;
		
		private string _OBSERVACIONES;
		
		private string _TRAMITADOR;
		
		private string _SOLICITANTE;
		
		private string _PROPIETARIO;
		
		private string _UBICACION;
		
		private string _NOTIFICACION;
		
		private bool _NOTIFICACION_RECHAZO;
		
		private System.Nullable<bool> _AVALUO;
		
		private string _FOLIO_PAGO_AVALUO;
		
		private System.Nullable<bool> _IGUAL_CARTOGRAFIA;
		
		private string _CORREOELECTRONICO;
		
		private System.Nullable<int> _CONTROLFOLIO;
		
		private string _PROPIETARIO_CURP;
		
		private string _PROPIETARIO_RFC;
		
		private string _PROPIETARIO_TELEFONO;
		
		private string _PROPIETARIO_DOMICILIO_CALLE;
		
		private string _PROPIETARIO_DOMICILIO_NO_EXT;
		
		private string _PROPIETARIO_DOMICILIO_COLONIA;
		
		private string _PROPIETARIO_DOMICILIO_CP;
		
		private string _PROPIETARIO_DOMICILIO_LOCALIDAD;
		
		private string _PROPIETARIO_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_DOMICILIO_CALLE;
		
		private string _INMUEBLE_DOMICILIO_NO_EXT;
		
		private string _INMUEBLE_DOMICILIO_COLONIA;
		
		private string _INMUEBLE_DOMICILIO_CP;
		
		private string _INMUEBLE_DOMICILIO_LOCALIDAD;
		
		private string _INMUEBLE_DOMICILIO_MUNICIPIO;
		
		private string _INMUEBLE_TIPO_PREDIO;
		
		private System.Nullable<decimal> _INMUEBLE_SUPERFICIE_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_CONCRETO_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TEJABAN_M2;
		
		private System.Nullable<decimal> _INMUEBLE_CONSTRUCCION_TOTAL_M2;
		
		private string _INMUEBLE_AVANCE_OBRA;
		
		private string _INMUEBLE_ESTADO_CONSERVACION;
		
		private System.Nullable<int> _INMUEBLE_ANTIGUEDAD_ANIOS;
		
		private string _INMUEBLE_TIPO_USO;
		
		private string _INMUEBLE_TIPO_INDUSTRIAL;
		
		private string _INMUEBLE_COMERCIAL_Y_SERVICIO;
		
		private string _PROPIETARIO_DOMICILIO_NO_INT;
		
		private string _INMUEBLE_DOMICILIO_NO_INT;
		
		private string _LOTE;
		
		private string _MANZANA;
		
		private string _INDIVISO;
		
		private string _FOLIOREAL;
		
		private System.Nullable<decimal> _CORDENADAX;
		
		private System.Nullable<decimal> _CORDENADAY;
		
		public SIS_TRACAT_SOLICITUD_MC_AV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(200)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(200)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_TRAMITE", DbType="NVarChar(30)")]
		public string FOLIO_TRAMITE
		{
			get
			{
				return this._FOLIO_TRAMITE;
			}
			set
			{
				if ((this._FOLIO_TRAMITE != value))
				{
					this._FOLIO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_TRAMITE", DbType="NVarChar(200)")]
		public string TIPO_TRAMITE
		{
			get
			{
				return this._TIPO_TRAMITE;
			}
			set
			{
				if ((this._TIPO_TRAMITE != value))
				{
					this._TIPO_TRAMITE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(31)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_PREDIAL", DbType="NVarChar(30)")]
		public string CVE_PREDIAL
		{
			get
			{
				return this._CVE_PREDIAL;
			}
			set
			{
				if ((this._CVE_PREDIAL != value))
				{
					this._CVE_PREDIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="NVarChar(MAX)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAMITADOR", DbType="NVarChar(200)")]
		public string TRAMITADOR
		{
			get
			{
				return this._TRAMITADOR;
			}
			set
			{
				if ((this._TRAMITADOR != value))
				{
					this._TRAMITADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITANTE", DbType="NVarChar(255)")]
		public string SOLICITANTE
		{
			get
			{
				return this._SOLICITANTE;
			}
			set
			{
				if ((this._SOLICITANTE != value))
				{
					this._SOLICITANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO", DbType="VarChar(200)")]
		public string PROPIETARIO
		{
			get
			{
				return this._PROPIETARIO;
			}
			set
			{
				if ((this._PROPIETARIO != value))
				{
					this._PROPIETARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION", DbType="NVarChar(MAX)")]
		public string UBICACION
		{
			get
			{
				return this._UBICACION;
			}
			set
			{
				if ((this._UBICACION != value))
				{
					this._UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFICACION", DbType="VarChar(250)")]
		public string NOTIFICACION
		{
			get
			{
				return this._NOTIFICACION;
			}
			set
			{
				if ((this._NOTIFICACION != value))
				{
					this._NOTIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFICACION_RECHAZO", DbType="Bit NOT NULL")]
		public bool NOTIFICACION_RECHAZO
		{
			get
			{
				return this._NOTIFICACION_RECHAZO;
			}
			set
			{
				if ((this._NOTIFICACION_RECHAZO != value))
				{
					this._NOTIFICACION_RECHAZO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVALUO", DbType="Bit")]
		public System.Nullable<bool> AVALUO
		{
			get
			{
				return this._AVALUO;
			}
			set
			{
				if ((this._AVALUO != value))
				{
					this._AVALUO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_PAGO_AVALUO", DbType="VarChar(50)")]
		public string FOLIO_PAGO_AVALUO
		{
			get
			{
				return this._FOLIO_PAGO_AVALUO;
			}
			set
			{
				if ((this._FOLIO_PAGO_AVALUO != value))
				{
					this._FOLIO_PAGO_AVALUO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGUAL_CARTOGRAFIA", DbType="Bit")]
		public System.Nullable<bool> IGUAL_CARTOGRAFIA
		{
			get
			{
				return this._IGUAL_CARTOGRAFIA;
			}
			set
			{
				if ((this._IGUAL_CARTOGRAFIA != value))
				{
					this._IGUAL_CARTOGRAFIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREOELECTRONICO", DbType="VarChar(255)")]
		public string CORREOELECTRONICO
		{
			get
			{
				return this._CORREOELECTRONICO;
			}
			set
			{
				if ((this._CORREOELECTRONICO != value))
				{
					this._CORREOELECTRONICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLFOLIO", DbType="Int")]
		public System.Nullable<int> CONTROLFOLIO
		{
			get
			{
				return this._CONTROLFOLIO;
			}
			set
			{
				if ((this._CONTROLFOLIO != value))
				{
					this._CONTROLFOLIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_CURP", DbType="NVarChar(255)")]
		public string PROPIETARIO_CURP
		{
			get
			{
				return this._PROPIETARIO_CURP;
			}
			set
			{
				if ((this._PROPIETARIO_CURP != value))
				{
					this._PROPIETARIO_CURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_RFC", DbType="NVarChar(255)")]
		public string PROPIETARIO_RFC
		{
			get
			{
				return this._PROPIETARIO_RFC;
			}
			set
			{
				if ((this._PROPIETARIO_RFC != value))
				{
					this._PROPIETARIO_RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_TELEFONO", DbType="NVarChar(20)")]
		public string PROPIETARIO_TELEFONO
		{
			get
			{
				return this._PROPIETARIO_TELEFONO;
			}
			set
			{
				if ((this._PROPIETARIO_TELEFONO != value))
				{
					this._PROPIETARIO_TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_CALLE
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CALLE != value))
				{
					this._PROPIETARIO_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_NO_EXT
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_NO_EXT != value))
				{
					this._PROPIETARIO_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_COLONIA
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_COLONIA != value))
				{
					this._PROPIETARIO_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_CP
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_CP;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_CP != value))
				{
					this._PROPIETARIO_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_LOCALIDAD != value))
				{
					this._PROPIETARIO_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string PROPIETARIO_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_MUNICIPIO != value))
				{
					this._PROPIETARIO_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CALLE", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_CALLE
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CALLE;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CALLE != value))
				{
					this._INMUEBLE_DOMICILIO_CALLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_NO_EXT", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_NO_EXT
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_NO_EXT;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_NO_EXT != value))
				{
					this._INMUEBLE_DOMICILIO_NO_EXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_COLONIA", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_COLONIA
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_COLONIA;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_COLONIA != value))
				{
					this._INMUEBLE_DOMICILIO_COLONIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_CP", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_CP
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_CP;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_CP != value))
				{
					this._INMUEBLE_DOMICILIO_CP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_LOCALIDAD", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_LOCALIDAD
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_LOCALIDAD;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_LOCALIDAD != value))
				{
					this._INMUEBLE_DOMICILIO_LOCALIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_MUNICIPIO", DbType="NVarChar(255)")]
		public string INMUEBLE_DOMICILIO_MUNICIPIO
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_MUNICIPIO;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_MUNICIPIO != value))
				{
					this._INMUEBLE_DOMICILIO_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_PREDIO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_PREDIO
		{
			get
			{
				return this._INMUEBLE_TIPO_PREDIO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_PREDIO != value))
				{
					this._INMUEBLE_TIPO_PREDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_SUPERFICIE_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_SUPERFICIE_M2
		{
			get
			{
				return this._INMUEBLE_SUPERFICIE_M2;
			}
			set
			{
				if ((this._INMUEBLE_SUPERFICIE_M2 != value))
				{
					this._INMUEBLE_SUPERFICIE_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_CONCRETO_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_CONCRETO_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_CONCRETO_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_CONCRETO_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TEJABAN_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TEJABAN_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TEJABAN_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TEJABAN_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_CONSTRUCCION_TOTAL_M2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> INMUEBLE_CONSTRUCCION_TOTAL_M2
		{
			get
			{
				return this._INMUEBLE_CONSTRUCCION_TOTAL_M2;
			}
			set
			{
				if ((this._INMUEBLE_CONSTRUCCION_TOTAL_M2 != value))
				{
					this._INMUEBLE_CONSTRUCCION_TOTAL_M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_AVANCE_OBRA", DbType="NVarChar(50)")]
		public string INMUEBLE_AVANCE_OBRA
		{
			get
			{
				return this._INMUEBLE_AVANCE_OBRA;
			}
			set
			{
				if ((this._INMUEBLE_AVANCE_OBRA != value))
				{
					this._INMUEBLE_AVANCE_OBRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ESTADO_CONSERVACION", DbType="NVarChar(50)")]
		public string INMUEBLE_ESTADO_CONSERVACION
		{
			get
			{
				return this._INMUEBLE_ESTADO_CONSERVACION;
			}
			set
			{
				if ((this._INMUEBLE_ESTADO_CONSERVACION != value))
				{
					this._INMUEBLE_ESTADO_CONSERVACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_ANTIGUEDAD_ANIOS", DbType="Int")]
		public System.Nullable<int> INMUEBLE_ANTIGUEDAD_ANIOS
		{
			get
			{
				return this._INMUEBLE_ANTIGUEDAD_ANIOS;
			}
			set
			{
				if ((this._INMUEBLE_ANTIGUEDAD_ANIOS != value))
				{
					this._INMUEBLE_ANTIGUEDAD_ANIOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_USO", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_USO
		{
			get
			{
				return this._INMUEBLE_TIPO_USO;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_USO != value))
				{
					this._INMUEBLE_TIPO_USO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_TIPO_INDUSTRIAL", DbType="NVarChar(50)")]
		public string INMUEBLE_TIPO_INDUSTRIAL
		{
			get
			{
				return this._INMUEBLE_TIPO_INDUSTRIAL;
			}
			set
			{
				if ((this._INMUEBLE_TIPO_INDUSTRIAL != value))
				{
					this._INMUEBLE_TIPO_INDUSTRIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_COMERCIAL_Y_SERVICIO", DbType="NVarChar(50)")]
		public string INMUEBLE_COMERCIAL_Y_SERVICIO
		{
			get
			{
				return this._INMUEBLE_COMERCIAL_Y_SERVICIO;
			}
			set
			{
				if ((this._INMUEBLE_COMERCIAL_Y_SERVICIO != value))
				{
					this._INMUEBLE_COMERCIAL_Y_SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPIETARIO_DOMICILIO_NO_INT", DbType="NVarChar(10)")]
		public string PROPIETARIO_DOMICILIO_NO_INT
		{
			get
			{
				return this._PROPIETARIO_DOMICILIO_NO_INT;
			}
			set
			{
				if ((this._PROPIETARIO_DOMICILIO_NO_INT != value))
				{
					this._PROPIETARIO_DOMICILIO_NO_INT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INMUEBLE_DOMICILIO_NO_INT", DbType="NVarChar(10)")]
		public string INMUEBLE_DOMICILIO_NO_INT
		{
			get
			{
				return this._INMUEBLE_DOMICILIO_NO_INT;
			}
			set
			{
				if ((this._INMUEBLE_DOMICILIO_NO_INT != value))
				{
					this._INMUEBLE_DOMICILIO_NO_INT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOTE", DbType="NVarChar(50)")]
		public string LOTE
		{
			get
			{
				return this._LOTE;
			}
			set
			{
				if ((this._LOTE != value))
				{
					this._LOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANZANA", DbType="NVarChar(50)")]
		public string MANZANA
		{
			get
			{
				return this._MANZANA;
			}
			set
			{
				if ((this._MANZANA != value))
				{
					this._MANZANA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDIVISO", DbType="NVarChar(50)")]
		public string INDIVISO
		{
			get
			{
				return this._INDIVISO;
			}
			set
			{
				if ((this._INDIVISO != value))
				{
					this._INDIVISO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIOREAL", DbType="NVarChar(50)")]
		public string FOLIOREAL
		{
			get
			{
				return this._FOLIOREAL;
			}
			set
			{
				if ((this._FOLIOREAL != value))
				{
					this._FOLIOREAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORDENADAX", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> CORDENADAX
		{
			get
			{
				return this._CORDENADAX;
			}
			set
			{
				if ((this._CORDENADAX != value))
				{
					this._CORDENADAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORDENADAY", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> CORDENADAY
		{
			get
			{
				return this._CORDENADAY;
			}
			set
			{
				if ((this._CORDENADAY != value))
				{
					this._CORDENADAY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
