//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.PagosCaja {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagosCaja.WSResguardosSoap")]
    public interface WSResguardosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumeroEmpleado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResguardoEmpleado", ReplyAction="*")]
        ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse GetResguardoEmpleado(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResguardoEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse> GetResguardoEmpleadoAsync(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumeroBienes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBienes", ReplyAction="*")]
        ManifestacionEnLinea.PagosCaja.GetBienesResponse GetBienes(ManifestacionEnLinea.PagosCaja.GetBienesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBienes", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetBienesResponse> GetBienesAsync(ManifestacionEnLinea.PagosCaja.GetBienesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FolioReciboSefi del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformacionRecibo", ReplyAction="*")]
        ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse getInformacionRecibo(ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformacionRecibo", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse> getInformacionReciboAsync(ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FolioReciboSefi del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usarFolioRecibo", ReplyAction="*")]
        ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse usarFolioRecibo(ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usarFolioRecibo", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse> usarFolioReciboAsync(ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cadenaoriginal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/firmar", ReplyAction="*")]
        ManifestacionEnLinea.PagosCaja.firmarResponse firmar(ManifestacionEnLinea.PagosCaja.firmarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/firmar", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.firmarResponse> firmarAsync(ManifestacionEnLinea.PagosCaja.firmarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResguardoEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResguardoEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequestBody Body;
        
        public GetResguardoEmpleadoRequest() {
        }
        
        public GetResguardoEmpleadoRequest(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResguardoEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumeroEmpleado;
        
        public GetResguardoEmpleadoRequestBody() {
        }
        
        public GetResguardoEmpleadoRequestBody(string NumeroEmpleado) {
            this.NumeroEmpleado = NumeroEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResguardoEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResguardoEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponseBody Body;
        
        public GetResguardoEmpleadoResponse() {
        }
        
        public GetResguardoEmpleadoResponse(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResguardoEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResguardoEmpleadoResult;
        
        public GetResguardoEmpleadoResponseBody() {
        }
        
        public GetResguardoEmpleadoResponseBody(string GetResguardoEmpleadoResult) {
            this.GetResguardoEmpleadoResult = GetResguardoEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBienesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBienes", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.GetBienesRequestBody Body;
        
        public GetBienesRequest() {
        }
        
        public GetBienesRequest(ManifestacionEnLinea.PagosCaja.GetBienesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBienesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumeroBienes;
        
        public GetBienesRequestBody() {
        }
        
        public GetBienesRequestBody(string NumeroBienes) {
            this.NumeroBienes = NumeroBienes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBienesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBienesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.GetBienesResponseBody Body;
        
        public GetBienesResponse() {
        }
        
        public GetBienesResponse(ManifestacionEnLinea.PagosCaja.GetBienesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBienesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBienesResult;
        
        public GetBienesResponseBody() {
        }
        
        public GetBienesResponseBody(string GetBienesResult) {
            this.GetBienesResult = GetBienesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformacionReciboRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformacionRecibo", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.getInformacionReciboRequestBody Body;
        
        public getInformacionReciboRequest() {
        }
        
        public getInformacionReciboRequest(ManifestacionEnLinea.PagosCaja.getInformacionReciboRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInformacionReciboRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FolioReciboSefi;
        
        public getInformacionReciboRequestBody() {
        }
        
        public getInformacionReciboRequestBody(string FolioReciboSefi) {
            this.FolioReciboSefi = FolioReciboSefi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformacionReciboResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformacionReciboResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.getInformacionReciboResponseBody Body;
        
        public getInformacionReciboResponse() {
        }
        
        public getInformacionReciboResponse(ManifestacionEnLinea.PagosCaja.getInformacionReciboResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInformacionReciboResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInformacionReciboResult;
        
        public getInformacionReciboResponseBody() {
        }
        
        public getInformacionReciboResponseBody(string getInformacionReciboResult) {
            this.getInformacionReciboResult = getInformacionReciboResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class usarFolioReciboRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="usarFolioRecibo", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.usarFolioReciboRequestBody Body;
        
        public usarFolioReciboRequest() {
        }
        
        public usarFolioReciboRequest(ManifestacionEnLinea.PagosCaja.usarFolioReciboRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class usarFolioReciboRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FolioReciboSefi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FolioTramite;
        
        public usarFolioReciboRequestBody() {
        }
        
        public usarFolioReciboRequestBody(string FolioReciboSefi, string FolioTramite) {
            this.FolioReciboSefi = FolioReciboSefi;
            this.FolioTramite = FolioTramite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class usarFolioReciboResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="usarFolioReciboResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.usarFolioReciboResponseBody Body;
        
        public usarFolioReciboResponse() {
        }
        
        public usarFolioReciboResponse(ManifestacionEnLinea.PagosCaja.usarFolioReciboResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class usarFolioReciboResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usarFolioReciboResult;
        
        public usarFolioReciboResponseBody() {
        }
        
        public usarFolioReciboResponseBody(string usarFolioReciboResult) {
            this.usarFolioReciboResult = usarFolioReciboResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class firmarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="firmar", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.firmarRequestBody Body;
        
        public firmarRequest() {
        }
        
        public firmarRequest(ManifestacionEnLinea.PagosCaja.firmarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class firmarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cadenaoriginal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NombreParametro;
        
        public firmarRequestBody() {
        }
        
        public firmarRequestBody(string cadenaoriginal, string NombreParametro) {
            this.cadenaoriginal = cadenaoriginal;
            this.NombreParametro = NombreParametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class firmarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="firmarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.PagosCaja.firmarResponseBody Body;
        
        public firmarResponse() {
        }
        
        public firmarResponse(ManifestacionEnLinea.PagosCaja.firmarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class firmarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firmarResult;
        
        public firmarResponseBody() {
        }
        
        public firmarResponseBody(string firmarResult) {
            this.firmarResult = firmarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSResguardosSoapChannel : ManifestacionEnLinea.PagosCaja.WSResguardosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSResguardosSoapClient : System.ServiceModel.ClientBase<ManifestacionEnLinea.PagosCaja.WSResguardosSoap>, ManifestacionEnLinea.PagosCaja.WSResguardosSoap {
        
        public WSResguardosSoapClient() {
        }
        
        public WSResguardosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSResguardosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSResguardosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSResguardosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse ManifestacionEnLinea.PagosCaja.WSResguardosSoap.GetResguardoEmpleado(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest request) {
            return base.Channel.GetResguardoEmpleado(request);
        }
        
        public string GetResguardoEmpleado(string NumeroEmpleado) {
            ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest inValue = new ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequestBody();
            inValue.Body.NumeroEmpleado = NumeroEmpleado;
            ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse retVal = ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).GetResguardoEmpleado(inValue);
            return retVal.Body.GetResguardoEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse> ManifestacionEnLinea.PagosCaja.WSResguardosSoap.GetResguardoEmpleadoAsync(ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest request) {
            return base.Channel.GetResguardoEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoResponse> GetResguardoEmpleadoAsync(string NumeroEmpleado) {
            ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest inValue = new ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.GetResguardoEmpleadoRequestBody();
            inValue.Body.NumeroEmpleado = NumeroEmpleado;
            return ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).GetResguardoEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.PagosCaja.GetBienesResponse ManifestacionEnLinea.PagosCaja.WSResguardosSoap.GetBienes(ManifestacionEnLinea.PagosCaja.GetBienesRequest request) {
            return base.Channel.GetBienes(request);
        }
        
        public string GetBienes(string NumeroBienes) {
            ManifestacionEnLinea.PagosCaja.GetBienesRequest inValue = new ManifestacionEnLinea.PagosCaja.GetBienesRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.GetBienesRequestBody();
            inValue.Body.NumeroBienes = NumeroBienes;
            ManifestacionEnLinea.PagosCaja.GetBienesResponse retVal = ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).GetBienes(inValue);
            return retVal.Body.GetBienesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetBienesResponse> ManifestacionEnLinea.PagosCaja.WSResguardosSoap.GetBienesAsync(ManifestacionEnLinea.PagosCaja.GetBienesRequest request) {
            return base.Channel.GetBienesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.GetBienesResponse> GetBienesAsync(string NumeroBienes) {
            ManifestacionEnLinea.PagosCaja.GetBienesRequest inValue = new ManifestacionEnLinea.PagosCaja.GetBienesRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.GetBienesRequestBody();
            inValue.Body.NumeroBienes = NumeroBienes;
            return ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).GetBienesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse ManifestacionEnLinea.PagosCaja.WSResguardosSoap.getInformacionRecibo(ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest request) {
            return base.Channel.getInformacionRecibo(request);
        }
        
        public string getInformacionRecibo(string FolioReciboSefi) {
            ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest inValue = new ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.getInformacionReciboRequestBody();
            inValue.Body.FolioReciboSefi = FolioReciboSefi;
            ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse retVal = ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).getInformacionRecibo(inValue);
            return retVal.Body.getInformacionReciboResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse> ManifestacionEnLinea.PagosCaja.WSResguardosSoap.getInformacionReciboAsync(ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest request) {
            return base.Channel.getInformacionReciboAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.getInformacionReciboResponse> getInformacionReciboAsync(string FolioReciboSefi) {
            ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest inValue = new ManifestacionEnLinea.PagosCaja.getInformacionReciboRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.getInformacionReciboRequestBody();
            inValue.Body.FolioReciboSefi = FolioReciboSefi;
            return ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).getInformacionReciboAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse ManifestacionEnLinea.PagosCaja.WSResguardosSoap.usarFolioRecibo(ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest request) {
            return base.Channel.usarFolioRecibo(request);
        }
        
        public string usarFolioRecibo(string FolioReciboSefi, string FolioTramite) {
            ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest inValue = new ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.usarFolioReciboRequestBody();
            inValue.Body.FolioReciboSefi = FolioReciboSefi;
            inValue.Body.FolioTramite = FolioTramite;
            ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse retVal = ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).usarFolioRecibo(inValue);
            return retVal.Body.usarFolioReciboResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse> ManifestacionEnLinea.PagosCaja.WSResguardosSoap.usarFolioReciboAsync(ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest request) {
            return base.Channel.usarFolioReciboAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.usarFolioReciboResponse> usarFolioReciboAsync(string FolioReciboSefi, string FolioTramite) {
            ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest inValue = new ManifestacionEnLinea.PagosCaja.usarFolioReciboRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.usarFolioReciboRequestBody();
            inValue.Body.FolioReciboSefi = FolioReciboSefi;
            inValue.Body.FolioTramite = FolioTramite;
            return ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).usarFolioReciboAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.PagosCaja.firmarResponse ManifestacionEnLinea.PagosCaja.WSResguardosSoap.firmar(ManifestacionEnLinea.PagosCaja.firmarRequest request) {
            return base.Channel.firmar(request);
        }
        
        public string firmar(string cadenaoriginal, string NombreParametro) {
            ManifestacionEnLinea.PagosCaja.firmarRequest inValue = new ManifestacionEnLinea.PagosCaja.firmarRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.firmarRequestBody();
            inValue.Body.cadenaoriginal = cadenaoriginal;
            inValue.Body.NombreParametro = NombreParametro;
            ManifestacionEnLinea.PagosCaja.firmarResponse retVal = ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).firmar(inValue);
            return retVal.Body.firmarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.firmarResponse> ManifestacionEnLinea.PagosCaja.WSResguardosSoap.firmarAsync(ManifestacionEnLinea.PagosCaja.firmarRequest request) {
            return base.Channel.firmarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.PagosCaja.firmarResponse> firmarAsync(string cadenaoriginal, string NombreParametro) {
            ManifestacionEnLinea.PagosCaja.firmarRequest inValue = new ManifestacionEnLinea.PagosCaja.firmarRequest();
            inValue.Body = new ManifestacionEnLinea.PagosCaja.firmarRequestBody();
            inValue.Body.cadenaoriginal = cadenaoriginal;
            inValue.Body.NombreParametro = NombreParametro;
            return ((ManifestacionEnLinea.PagosCaja.WSResguardosSoap)(this)).firmarAsync(inValue);
        }
    }
}
