#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GDB01001")]
	public partial class GDB01001DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public GDB01001DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GDB01001ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GDB01001DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GDB01001DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GDB01001DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GDB01001DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SIS_PC_CLAVE_CATASTRAL> SIS_PC_CLAVE_CATASTRAL
		{
			get
			{
				return this.GetTable<SIS_PC_CLAVE_CATASTRAL>();
			}
		}
		
		public System.Data.Linq.Table<SIS_PC_CONSTRUCCIONES2> SIS_PC_CONSTRUCCIONES2
		{
			get
			{
				return this.GetTable<SIS_PC_CONSTRUCCIONES2>();
			}
		}
		
		public System.Data.Linq.Table<SIS_PC_SUPERFICIES2> SIS_PC_SUPERFICIES2
		{
			get
			{
				return this.GetTable<SIS_PC_SUPERFICIES2>();
			}
		}
		
		public System.Data.Linq.Table<SIS_PC_CENTROIDES> SIS_PC_CENTROIDES
		{
			get
			{
				return this.GetTable<SIS_PC_CENTROIDES>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sde.SIS_PC_CLAVE_CATASTRAL")]
	public partial class SIS_PC_CLAVE_CATASTRAL
	{
		
		private int _OBJECTID;
		
		private System.Nullable<int> _CLAVEUNICA;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _HORAALTAREGISTROTABLA;
		
		private string _HORABAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _TERMINALALTA;
		
		private string _TERMINALBAJA;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private System.Nullable<System.DateTime> _FECHA_REGISTRO;
		
		private string _CVE_CAT_EST_ANT;
		
		private string _CVE_CAT_ANT;
		
		private string _CVE_PREDIAL;
		
		private string _REGIMEN_PREDIAL;
		
		private System.Nullable<System.DateTime> _FCH_INSCRIP_RPP;
		
		private string _FOLIO_REAL;
		
		private string _LEVANTAMIENTO;
		
		private string _TD;
		
		private string _MANIFESTACION;
		
		private string _TITULO_RAN;
		
		private string _VOLUMEN;
		
		private string _ESCRITURA;
		
		public SIS_PC_CLAVE_CATASTRAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVEUNICA", DbType="Int")]
		public System.Nullable<int> CLAVEUNICA
		{
			get
			{
				return this._CLAVEUNICA;
			}
			set
			{
				if ((this._CLAVEUNICA != value))
				{
					this._CLAVEUNICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAALTAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORAALTAREGISTROTABLA
		{
			get
			{
				return this._HORAALTAREGISTROTABLA;
			}
			set
			{
				if ((this._HORAALTAREGISTROTABLA != value))
				{
					this._HORAALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORABAJAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORABAJAREGISTROTABLA
		{
			get
			{
				return this._HORABAJAREGISTROTABLA;
			}
			set
			{
				if ((this._HORABAJAREGISTROTABLA != value))
				{
					this._HORABAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(50)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(50)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALALTA", DbType="NVarChar(50)")]
		public string TERMINALALTA
		{
			get
			{
				return this._TERMINALALTA;
			}
			set
			{
				if ((this._TERMINALALTA != value))
				{
					this._TERMINALALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALBAJA", DbType="NVarChar(50)")]
		public string TERMINALBAJA
		{
			get
			{
				return this._TERMINALBAJA;
			}
			set
			{
				if ((this._TERMINALBAJA != value))
				{
					this._TERMINALBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(30)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST_ANT", DbType="NVarChar(31)")]
		public string CVE_CAT_EST_ANT
		{
			get
			{
				return this._CVE_CAT_EST_ANT;
			}
			set
			{
				if ((this._CVE_CAT_EST_ANT != value))
				{
					this._CVE_CAT_EST_ANT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ANT", DbType="NVarChar(30)")]
		public string CVE_CAT_ANT
		{
			get
			{
				return this._CVE_CAT_ANT;
			}
			set
			{
				if ((this._CVE_CAT_ANT != value))
				{
					this._CVE_CAT_ANT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_PREDIAL", DbType="NVarChar(30)")]
		public string CVE_PREDIAL
		{
			get
			{
				return this._CVE_PREDIAL;
			}
			set
			{
				if ((this._CVE_PREDIAL != value))
				{
					this._CVE_PREDIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIMEN_PREDIAL", DbType="NVarChar(200)")]
		public string REGIMEN_PREDIAL
		{
			get
			{
				return this._REGIMEN_PREDIAL;
			}
			set
			{
				if ((this._REGIMEN_PREDIAL != value))
				{
					this._REGIMEN_PREDIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCH_INSCRIP_RPP", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FCH_INSCRIP_RPP
		{
			get
			{
				return this._FCH_INSCRIP_RPP;
			}
			set
			{
				if ((this._FCH_INSCRIP_RPP != value))
				{
					this._FCH_INSCRIP_RPP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO_REAL", DbType="NVarChar(30)")]
		public string FOLIO_REAL
		{
			get
			{
				return this._FOLIO_REAL;
			}
			set
			{
				if ((this._FOLIO_REAL != value))
				{
					this._FOLIO_REAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEVANTAMIENTO", DbType="NVarChar(50)")]
		public string LEVANTAMIENTO
		{
			get
			{
				return this._LEVANTAMIENTO;
			}
			set
			{
				if ((this._LEVANTAMIENTO != value))
				{
					this._LEVANTAMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TD", DbType="NVarChar(50)")]
		public string TD
		{
			get
			{
				return this._TD;
			}
			set
			{
				if ((this._TD != value))
				{
					this._TD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANIFESTACION", DbType="NVarChar(50)")]
		public string MANIFESTACION
		{
			get
			{
				return this._MANIFESTACION;
			}
			set
			{
				if ((this._MANIFESTACION != value))
				{
					this._MANIFESTACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO_RAN", DbType="NVarChar(50)")]
		public string TITULO_RAN
		{
			get
			{
				return this._TITULO_RAN;
			}
			set
			{
				if ((this._TITULO_RAN != value))
				{
					this._TITULO_RAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUMEN", DbType="NVarChar(50)")]
		public string VOLUMEN
		{
			get
			{
				return this._VOLUMEN;
			}
			set
			{
				if ((this._VOLUMEN != value))
				{
					this._VOLUMEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESCRITURA", DbType="NVarChar(50)")]
		public string ESCRITURA
		{
			get
			{
				return this._ESCRITURA;
			}
			set
			{
				if ((this._ESCRITURA != value))
				{
					this._ESCRITURA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sde.SIS_PC_CONSTRUCCIONES2")]
	public partial class SIS_PC_CONSTRUCCIONES2
	{
		
		private int _OBJECTID;
		
		private System.Nullable<int> _CLAVEUNICA;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _HORAALTAREGISTROTABLA;
		
		private string _HORABAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _TERMINALALTA;
		
		private string _TERMINALBAJA;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _TIPO;
		
		private string _DESCRIPCION_TIPO;
		
		private string _ESTADO;
		
		private string _DESCRIPCION_ESTADO;
		
		private System.Nullable<int> _ANIO;
		
		private System.Nullable<decimal> _FACTOR_EDAD;
		
		private string _AVANCE;
		
		private string _DESCRIPCION_AVANCE;
		
		private System.Nullable<decimal> _FACTOR_AVANCE;
		
		private System.Nullable<decimal> _AREA;
		
		private System.Nullable<decimal> _VALOR_UNITARIO;
		
		private System.Nullable<decimal> _VALOR_PARCIAL;
		
		public SIS_PC_CONSTRUCCIONES2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVEUNICA", DbType="Int")]
		public System.Nullable<int> CLAVEUNICA
		{
			get
			{
				return this._CLAVEUNICA;
			}
			set
			{
				if ((this._CLAVEUNICA != value))
				{
					this._CLAVEUNICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(50)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAALTAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORAALTAREGISTROTABLA
		{
			get
			{
				return this._HORAALTAREGISTROTABLA;
			}
			set
			{
				if ((this._HORAALTAREGISTROTABLA != value))
				{
					this._HORAALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORABAJAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORABAJAREGISTROTABLA
		{
			get
			{
				return this._HORABAJAREGISTROTABLA;
			}
			set
			{
				if ((this._HORABAJAREGISTROTABLA != value))
				{
					this._HORABAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(50)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(50)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALALTA", DbType="NVarChar(50)")]
		public string TERMINALALTA
		{
			get
			{
				return this._TERMINALALTA;
			}
			set
			{
				if ((this._TERMINALALTA != value))
				{
					this._TERMINALALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALBAJA", DbType="NVarChar(50)")]
		public string TERMINALBAJA
		{
			get
			{
				return this._TERMINALBAJA;
			}
			set
			{
				if ((this._TERMINALBAJA != value))
				{
					this._TERMINALBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(30)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="NVarChar(3)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_TIPO", DbType="NVarChar(200)")]
		public string DESCRIPCION_TIPO
		{
			get
			{
				return this._DESCRIPCION_TIPO;
			}
			set
			{
				if ((this._DESCRIPCION_TIPO != value))
				{
					this._DESCRIPCION_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_ESTADO", DbType="NVarChar(200)")]
		public string DESCRIPCION_ESTADO
		{
			get
			{
				return this._DESCRIPCION_ESTADO;
			}
			set
			{
				if ((this._DESCRIPCION_ESTADO != value))
				{
					this._DESCRIPCION_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANIO", DbType="Int")]
		public System.Nullable<int> ANIO
		{
			get
			{
				return this._ANIO;
			}
			set
			{
				if ((this._ANIO != value))
				{
					this._ANIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTOR_EDAD", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> FACTOR_EDAD
		{
			get
			{
				return this._FACTOR_EDAD;
			}
			set
			{
				if ((this._FACTOR_EDAD != value))
				{
					this._FACTOR_EDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVANCE", DbType="NVarChar(1)")]
		public string AVANCE
		{
			get
			{
				return this._AVANCE;
			}
			set
			{
				if ((this._AVANCE != value))
				{
					this._AVANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_AVANCE", DbType="NVarChar(200)")]
		public string DESCRIPCION_AVANCE
		{
			get
			{
				return this._DESCRIPCION_AVANCE;
			}
			set
			{
				if ((this._DESCRIPCION_AVANCE != value))
				{
					this._DESCRIPCION_AVANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTOR_AVANCE", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> FACTOR_AVANCE
		{
			get
			{
				return this._FACTOR_AVANCE;
			}
			set
			{
				if ((this._FACTOR_AVANCE != value))
				{
					this._FACTOR_AVANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this._AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_UNITARIO", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_UNITARIO
		{
			get
			{
				return this._VALOR_UNITARIO;
			}
			set
			{
				if ((this._VALOR_UNITARIO != value))
				{
					this._VALOR_UNITARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PARCIAL", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_PARCIAL
		{
			get
			{
				return this._VALOR_PARCIAL;
			}
			set
			{
				if ((this._VALOR_PARCIAL != value))
				{
					this._VALOR_PARCIAL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sde.SIS_PC_SUPERFICIES2")]
	public partial class SIS_PC_SUPERFICIES2
	{
		
		private int _OBJECTID;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _HORAALTAREGISTROTABLA;
		
		private string _HORABAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _TERMINALALTA;
		
		private string _TERMINALBAJA;
		
		private string _CVE_CAT_EST;
		
		private string _CVE_CAT_ORI;
		
		private string _CVE_MAESTRO_EST;
		
		private string _CVE_MAESTRO_ORI;
		
		private string _REGIMEN;
		
		private string _TIPO_CONDOMINIO;
		
		private string _TIPO_ELEMENTO;
		
		private string _TIPO_PREDIO;
		
		private string _CLASIFICACION_USO;
		
		private System.Nullable<short> _ES_LOTE_TIPO;
		
		private System.Nullable<decimal> _SUP_CONS_PRIV;
		
		private System.Nullable<decimal> _SUP_CONS_COMUN;
		
		private System.Nullable<decimal> _SUP_CONS_TOTAL;
		
		private System.Nullable<decimal> _SUP_TERR_PRIV;
		
		private System.Nullable<decimal> _SUP_TERR_COMUN;
		
		private System.Nullable<decimal> _SUP_TERR_TOTAL;
		
		private System.Nullable<decimal> _AREA_PRIV;
		
		private System.Nullable<decimal> _AREA_COMUN;
		
		private System.Nullable<decimal> _INDIVISO;
		
		private System.Nullable<decimal> _VALOR_UNITARIO_TERRENO;
		
		private System.Nullable<decimal> _VALOR_TERRENO_PRIV;
		
		private System.Nullable<decimal> _VALOR_TERRENO_COMUN;
		
		private System.Nullable<decimal> _VALOR_TOTAL_TERRENO;
		
		private System.Nullable<decimal> _VALOR_CONS_PRIV;
		
		private System.Nullable<decimal> _VALOR_CONS_COMUN;
		
		private System.Nullable<decimal> _VALOR_TOTAL_CONSTRUCCION;
		
		private System.Nullable<decimal> _VALOR_CATASTRAL;
		
		private System.Nullable<decimal> _SUP_LEVANTAMIENTO_TOPOGRAFICO;
		
		private string _FICHA_LEVANTAMIENTO_TOPOGRAFICO;
		
		private System.Nullable<int> _ANIO_LEVANTAMIENTO_TOPOGRAFICO;
		
		public SIS_PC_SUPERFICIES2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAALTAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORAALTAREGISTROTABLA
		{
			get
			{
				return this._HORAALTAREGISTROTABLA;
			}
			set
			{
				if ((this._HORAALTAREGISTROTABLA != value))
				{
					this._HORAALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORABAJAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORABAJAREGISTROTABLA
		{
			get
			{
				return this._HORABAJAREGISTROTABLA;
			}
			set
			{
				if ((this._HORABAJAREGISTROTABLA != value))
				{
					this._HORABAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(50)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(50)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALALTA", DbType="NVarChar(50)")]
		public string TERMINALALTA
		{
			get
			{
				return this._TERMINALALTA;
			}
			set
			{
				if ((this._TERMINALALTA != value))
				{
					this._TERMINALALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALBAJA", DbType="NVarChar(50)")]
		public string TERMINALBAJA
		{
			get
			{
				return this._TERMINALBAJA;
			}
			set
			{
				if ((this._TERMINALBAJA != value))
				{
					this._TERMINALBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_ORI", DbType="NVarChar(30)")]
		public string CVE_CAT_ORI
		{
			get
			{
				return this._CVE_CAT_ORI;
			}
			set
			{
				if ((this._CVE_CAT_ORI != value))
				{
					this._CVE_CAT_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_MAESTRO_EST", DbType="NVarChar(31)")]
		public string CVE_MAESTRO_EST
		{
			get
			{
				return this._CVE_MAESTRO_EST;
			}
			set
			{
				if ((this._CVE_MAESTRO_EST != value))
				{
					this._CVE_MAESTRO_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_MAESTRO_ORI", DbType="NVarChar(17)")]
		public string CVE_MAESTRO_ORI
		{
			get
			{
				return this._CVE_MAESTRO_ORI;
			}
			set
			{
				if ((this._CVE_MAESTRO_ORI != value))
				{
					this._CVE_MAESTRO_ORI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIMEN", DbType="NVarChar(15)")]
		public string REGIMEN
		{
			get
			{
				return this._REGIMEN;
			}
			set
			{
				if ((this._REGIMEN != value))
				{
					this._REGIMEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_CONDOMINIO", DbType="NVarChar(50)")]
		public string TIPO_CONDOMINIO
		{
			get
			{
				return this._TIPO_CONDOMINIO;
			}
			set
			{
				if ((this._TIPO_CONDOMINIO != value))
				{
					this._TIPO_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_ELEMENTO", DbType="NVarChar(50)")]
		public string TIPO_ELEMENTO
		{
			get
			{
				return this._TIPO_ELEMENTO;
			}
			set
			{
				if ((this._TIPO_ELEMENTO != value))
				{
					this._TIPO_ELEMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_PREDIO", DbType="NVarChar(20)")]
		public string TIPO_PREDIO
		{
			get
			{
				return this._TIPO_PREDIO;
			}
			set
			{
				if ((this._TIPO_PREDIO != value))
				{
					this._TIPO_PREDIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASIFICACION_USO", DbType="NVarChar(50)")]
		public string CLASIFICACION_USO
		{
			get
			{
				return this._CLASIFICACION_USO;
			}
			set
			{
				if ((this._CLASIFICACION_USO != value))
				{
					this._CLASIFICACION_USO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ES_LOTE_TIPO", DbType="SmallInt")]
		public System.Nullable<short> ES_LOTE_TIPO
		{
			get
			{
				return this._ES_LOTE_TIPO;
			}
			set
			{
				if ((this._ES_LOTE_TIPO != value))
				{
					this._ES_LOTE_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_CONS_PRIV", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_CONS_PRIV
		{
			get
			{
				return this._SUP_CONS_PRIV;
			}
			set
			{
				if ((this._SUP_CONS_PRIV != value))
				{
					this._SUP_CONS_PRIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_CONS_COMUN", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_CONS_COMUN
		{
			get
			{
				return this._SUP_CONS_COMUN;
			}
			set
			{
				if ((this._SUP_CONS_COMUN != value))
				{
					this._SUP_CONS_COMUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_CONS_TOTAL", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_CONS_TOTAL
		{
			get
			{
				return this._SUP_CONS_TOTAL;
			}
			set
			{
				if ((this._SUP_CONS_TOTAL != value))
				{
					this._SUP_CONS_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_TERR_PRIV", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_TERR_PRIV
		{
			get
			{
				return this._SUP_TERR_PRIV;
			}
			set
			{
				if ((this._SUP_TERR_PRIV != value))
				{
					this._SUP_TERR_PRIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_TERR_COMUN", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_TERR_COMUN
		{
			get
			{
				return this._SUP_TERR_COMUN;
			}
			set
			{
				if ((this._SUP_TERR_COMUN != value))
				{
					this._SUP_TERR_COMUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_TERR_TOTAL", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> SUP_TERR_TOTAL
		{
			get
			{
				return this._SUP_TERR_TOTAL;
			}
			set
			{
				if ((this._SUP_TERR_TOTAL != value))
				{
					this._SUP_TERR_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_PRIV", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> AREA_PRIV
		{
			get
			{
				return this._AREA_PRIV;
			}
			set
			{
				if ((this._AREA_PRIV != value))
				{
					this._AREA_PRIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_COMUN", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> AREA_COMUN
		{
			get
			{
				return this._AREA_COMUN;
			}
			set
			{
				if ((this._AREA_COMUN != value))
				{
					this._AREA_COMUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDIVISO", DbType="Decimal(38,10)")]
		public System.Nullable<decimal> INDIVISO
		{
			get
			{
				return this._INDIVISO;
			}
			set
			{
				if ((this._INDIVISO != value))
				{
					this._INDIVISO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_UNITARIO_TERRENO", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_UNITARIO_TERRENO
		{
			get
			{
				return this._VALOR_UNITARIO_TERRENO;
			}
			set
			{
				if ((this._VALOR_UNITARIO_TERRENO != value))
				{
					this._VALOR_UNITARIO_TERRENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TERRENO_PRIV", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_TERRENO_PRIV
		{
			get
			{
				return this._VALOR_TERRENO_PRIV;
			}
			set
			{
				if ((this._VALOR_TERRENO_PRIV != value))
				{
					this._VALOR_TERRENO_PRIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TERRENO_COMUN", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_TERRENO_COMUN
		{
			get
			{
				return this._VALOR_TERRENO_COMUN;
			}
			set
			{
				if ((this._VALOR_TERRENO_COMUN != value))
				{
					this._VALOR_TERRENO_COMUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_TERRENO", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_TOTAL_TERRENO
		{
			get
			{
				return this._VALOR_TOTAL_TERRENO;
			}
			set
			{
				if ((this._VALOR_TOTAL_TERRENO != value))
				{
					this._VALOR_TOTAL_TERRENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_CONS_PRIV", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_CONS_PRIV
		{
			get
			{
				return this._VALOR_CONS_PRIV;
			}
			set
			{
				if ((this._VALOR_CONS_PRIV != value))
				{
					this._VALOR_CONS_PRIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_CONS_COMUN", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_CONS_COMUN
		{
			get
			{
				return this._VALOR_CONS_COMUN;
			}
			set
			{
				if ((this._VALOR_CONS_COMUN != value))
				{
					this._VALOR_CONS_COMUN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_CONSTRUCCION", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_TOTAL_CONSTRUCCION
		{
			get
			{
				return this._VALOR_TOTAL_CONSTRUCCION;
			}
			set
			{
				if ((this._VALOR_TOTAL_CONSTRUCCION != value))
				{
					this._VALOR_TOTAL_CONSTRUCCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_CATASTRAL", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR_CATASTRAL
		{
			get
			{
				return this._VALOR_CATASTRAL;
			}
			set
			{
				if ((this._VALOR_CATASTRAL != value))
				{
					this._VALOR_CATASTRAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_LEVANTAMIENTO_TOPOGRAFICO", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> SUP_LEVANTAMIENTO_TOPOGRAFICO
		{
			get
			{
				return this._SUP_LEVANTAMIENTO_TOPOGRAFICO;
			}
			set
			{
				if ((this._SUP_LEVANTAMIENTO_TOPOGRAFICO != value))
				{
					this._SUP_LEVANTAMIENTO_TOPOGRAFICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FICHA_LEVANTAMIENTO_TOPOGRAFICO", DbType="NVarChar(50)")]
		public string FICHA_LEVANTAMIENTO_TOPOGRAFICO
		{
			get
			{
				return this._FICHA_LEVANTAMIENTO_TOPOGRAFICO;
			}
			set
			{
				if ((this._FICHA_LEVANTAMIENTO_TOPOGRAFICO != value))
				{
					this._FICHA_LEVANTAMIENTO_TOPOGRAFICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANIO_LEVANTAMIENTO_TOPOGRAFICO", DbType="Int")]
		public System.Nullable<int> ANIO_LEVANTAMIENTO_TOPOGRAFICO
		{
			get
			{
				return this._ANIO_LEVANTAMIENTO_TOPOGRAFICO;
			}
			set
			{
				if ((this._ANIO_LEVANTAMIENTO_TOPOGRAFICO != value))
				{
					this._ANIO_LEVANTAMIENTO_TOPOGRAFICO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sde.SIS_PC_CENTROIDES")]
	public partial class SIS_PC_CENTROIDES
	{
		
		private int _OBJECTID;
		
		private System.Nullable<int> _CLAVEUNICA;
		
		private string _STATUSREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _ALTAREGISTROTABLA;
		
		private System.Nullable<System.DateTime> _BAJAREGISTROTABLA;
		
		private string _HORAALTAREGISTROTABLA;
		
		private string _HORABAJAREGISTROTABLA;
		
		private string _USUARIOALTA;
		
		private string _USUARIOBAJA;
		
		private string _TERMINALALTA;
		
		private string _TERMINALBAJA;
		
		private string _CVE_CAT_EST;
		
		private string _PISO;
		
		private string _CENT_PRED_LAT;
		
		private string _CENT_PRED_LON;
		
		private System.Nullable<decimal> _CENT_PRED_X;
		
		private System.Nullable<decimal> _CENT_PRED_Y;
		
		public SIS_PC_CENTROIDES()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVEUNICA", DbType="Int")]
		public System.Nullable<int> CLAVEUNICA
		{
			get
			{
				return this._CLAVEUNICA;
			}
			set
			{
				if ((this._CLAVEUNICA != value))
				{
					this._CLAVEUNICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSREGISTROTABLA", DbType="NVarChar(10)")]
		public string STATUSREGISTROTABLA
		{
			get
			{
				return this._STATUSREGISTROTABLA;
			}
			set
			{
				if ((this._STATUSREGISTROTABLA != value))
				{
					this._STATUSREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALTAREGISTROTABLA
		{
			get
			{
				return this._ALTAREGISTROTABLA;
			}
			set
			{
				if ((this._ALTAREGISTROTABLA != value))
				{
					this._ALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAJAREGISTROTABLA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> BAJAREGISTROTABLA
		{
			get
			{
				return this._BAJAREGISTROTABLA;
			}
			set
			{
				if ((this._BAJAREGISTROTABLA != value))
				{
					this._BAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAALTAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORAALTAREGISTROTABLA
		{
			get
			{
				return this._HORAALTAREGISTROTABLA;
			}
			set
			{
				if ((this._HORAALTAREGISTROTABLA != value))
				{
					this._HORAALTAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORABAJAREGISTROTABLA", DbType="NVarChar(20)")]
		public string HORABAJAREGISTROTABLA
		{
			get
			{
				return this._HORABAJAREGISTROTABLA;
			}
			set
			{
				if ((this._HORABAJAREGISTROTABLA != value))
				{
					this._HORABAJAREGISTROTABLA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOALTA", DbType="NVarChar(50)")]
		public string USUARIOALTA
		{
			get
			{
				return this._USUARIOALTA;
			}
			set
			{
				if ((this._USUARIOALTA != value))
				{
					this._USUARIOALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIOBAJA", DbType="NVarChar(50)")]
		public string USUARIOBAJA
		{
			get
			{
				return this._USUARIOBAJA;
			}
			set
			{
				if ((this._USUARIOBAJA != value))
				{
					this._USUARIOBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALALTA", DbType="NVarChar(50)")]
		public string TERMINALALTA
		{
			get
			{
				return this._TERMINALALTA;
			}
			set
			{
				if ((this._TERMINALALTA != value))
				{
					this._TERMINALALTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINALBAJA", DbType="NVarChar(50)")]
		public string TERMINALBAJA
		{
			get
			{
				return this._TERMINALBAJA;
			}
			set
			{
				if ((this._TERMINALBAJA != value))
				{
					this._TERMINALBAJA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVE_CAT_EST", DbType="NVarChar(31)")]
		public string CVE_CAT_EST
		{
			get
			{
				return this._CVE_CAT_EST;
			}
			set
			{
				if ((this._CVE_CAT_EST != value))
				{
					this._CVE_CAT_EST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PISO", DbType="NVarChar(3)")]
		public string PISO
		{
			get
			{
				return this._PISO;
			}
			set
			{
				if ((this._PISO != value))
				{
					this._PISO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENT_PRED_LAT", DbType="NVarChar(20)")]
		public string CENT_PRED_LAT
		{
			get
			{
				return this._CENT_PRED_LAT;
			}
			set
			{
				if ((this._CENT_PRED_LAT != value))
				{
					this._CENT_PRED_LAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENT_PRED_LON", DbType="NVarChar(20)")]
		public string CENT_PRED_LON
		{
			get
			{
				return this._CENT_PRED_LON;
			}
			set
			{
				if ((this._CENT_PRED_LON != value))
				{
					this._CENT_PRED_LON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENT_PRED_X", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> CENT_PRED_X
		{
			get
			{
				return this._CENT_PRED_X;
			}
			set
			{
				if ((this._CENT_PRED_X != value))
				{
					this._CENT_PRED_X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENT_PRED_Y", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> CENT_PRED_Y
		{
			get
			{
				return this._CENT_PRED_Y;
			}
			set
			{
				if ((this._CENT_PRED_Y != value))
				{
					this._CENT_PRED_Y = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
