//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.ControlFolios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioSolicitud", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FolioSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folio_SICField;
        
        private System.Nullable<bool> mani_con_avaluoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombreSolicitante {
            get {
                return this.nombreSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreSolicitanteField, value) != true)) {
                    this.nombreSolicitanteField = value;
                    this.RaisePropertyChanged("nombreSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folio_SIC {
            get {
                return this.folio_SICField;
            }
            set {
                if ((object.ReferenceEquals(this.folio_SICField, value) != true)) {
                    this.folio_SICField = value;
                    this.RaisePropertyChanged("folio_SIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<bool> mani_con_avaluo {
            get {
                return this.mani_con_avaluoField;
            }
            set {
                if ((this.mani_con_avaluoField.Equals(value) != true)) {
                    this.mani_con_avaluoField = value;
                    this.RaisePropertyChanged("mani_con_avaluo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioResp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FolioResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        private int id_folioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_folio {
            get {
                return this.id_folioField;
            }
            set {
                if ((this.id_folioField.Equals(value) != true)) {
                    this.id_folioField = value;
                    this.RaisePropertyChanged("id_folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string res {
            get {
                return this.resField;
            }
            set {
                if ((object.ReferenceEquals(this.resField, value) != true)) {
                    this.resField = value;
                    this.RaisePropertyChanged("res");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlFolios.CatastroControlFoliosSoap")]
    public interface CatastroControlFoliosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clave del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminadoPorFolioSIC", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse MarcarComoTerminadoPorFolioSIC(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminadoPorFolioSIC", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse> MarcarComoTerminadoPorFolioSICAsync(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clave del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminado", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse MarcarComoTerminado(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminado", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse> MarcarComoTerminadoAsync(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolio", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.AgregarFolioResponse AgregarFolio(ManifestacionEnLinea.ControlFolios.AgregarFolioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolio", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioResponse> AgregarFolioAsync(ManifestacionEnLinea.ControlFolios.AgregarFolioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolioAvaluoCatastral", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolioAvaluoCatastral", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse> AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLevantamiento", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse AgregarLevantamiento(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLevantamiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse> AgregarLevantamientoAsync(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPlanoCertificado", ReplyAction="*")]
        ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse AgregarPlanoCertificado(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPlanoCertificado", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse> AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoPorFolioSICRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoPorFolioSIC", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequestBody Body;
        
        public MarcarComoTerminadoPorFolioSICRequest() {
        }
        
        public MarcarComoTerminadoPorFolioSICRequest(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoPorFolioSICRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folio_SIC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folio_SIC_mani;
        
        public MarcarComoTerminadoPorFolioSICRequestBody() {
        }
        
        public MarcarComoTerminadoPorFolioSICRequestBody(string clave, string folio_SIC, string folio_SIC_mani) {
            this.clave = clave;
            this.folio_SIC = folio_SIC;
            this.folio_SIC_mani = folio_SIC_mani;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoPorFolioSICResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoPorFolioSICResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponseBody Body;
        
        public MarcarComoTerminadoPorFolioSICResponse() {
        }
        
        public MarcarComoTerminadoPorFolioSICResponse(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoPorFolioSICResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarcarComoTerminadoPorFolioSICResult;
        
        public MarcarComoTerminadoPorFolioSICResponseBody() {
        }
        
        public MarcarComoTerminadoPorFolioSICResponseBody(string MarcarComoTerminadoPorFolioSICResult) {
            this.MarcarComoTerminadoPorFolioSICResult = MarcarComoTerminadoPorFolioSICResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminado", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequestBody Body;
        
        public MarcarComoTerminadoRequest() {
        }
        
        public MarcarComoTerminadoRequest(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folioSIC;
        
        public MarcarComoTerminadoRequestBody() {
        }
        
        public MarcarComoTerminadoRequestBody(string clave, string folioSIC) {
            this.clave = clave;
            this.folioSIC = folioSIC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponseBody Body;
        
        public MarcarComoTerminadoResponse() {
        }
        
        public MarcarComoTerminadoResponse(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarcarComoTerminadoResult;
        
        public MarcarComoTerminadoResponseBody() {
        }
        
        public MarcarComoTerminadoResponseBody(string MarcarComoTerminadoResult) {
            this.MarcarComoTerminadoResult = MarcarComoTerminadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolio", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarFolioRequestBody Body;
        
        public AgregarFolioRequest() {
        }
        
        public AgregarFolioRequest(ManifestacionEnLinea.ControlFolios.AgregarFolioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarFolioRequestBody() {
        }
        
        public AgregarFolioRequestBody(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarFolioResponseBody Body;
        
        public AgregarFolioResponse() {
        }
        
        public AgregarFolioResponse(ManifestacionEnLinea.ControlFolios.AgregarFolioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolioResult;
        
        public AgregarFolioResponseBody() {
        }
        
        public AgregarFolioResponseBody(ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolioResult) {
            this.AgregarFolioResult = AgregarFolioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioAvaluoCatastralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioAvaluoCatastral", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequestBody Body;
        
        public AgregarFolioAvaluoCatastralRequest() {
        }
        
        public AgregarFolioAvaluoCatastralRequest(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioAvaluoCatastralRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarFolioAvaluoCatastralRequestBody() {
        }
        
        public AgregarFolioAvaluoCatastralRequestBody(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioAvaluoCatastralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioAvaluoCatastralResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponseBody Body;
        
        public AgregarFolioAvaluoCatastralResponse() {
        }
        
        public AgregarFolioAvaluoCatastralResponse(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioAvaluoCatastralResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolioAvaluoCatastralResult;
        
        public AgregarFolioAvaluoCatastralResponseBody() {
        }
        
        public AgregarFolioAvaluoCatastralResponseBody(ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolioAvaluoCatastralResult) {
            this.AgregarFolioAvaluoCatastralResult = AgregarFolioAvaluoCatastralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLevantamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLevantamiento", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequestBody Body;
        
        public AgregarLevantamientoRequest() {
        }
        
        public AgregarLevantamientoRequest(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLevantamientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarLevantamientoRequestBody() {
        }
        
        public AgregarLevantamientoRequestBody(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLevantamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLevantamientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponseBody Body;
        
        public AgregarLevantamientoResponse() {
        }
        
        public AgregarLevantamientoResponse(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLevantamientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarLevantamientoResult;
        
        public AgregarLevantamientoResponseBody() {
        }
        
        public AgregarLevantamientoResponseBody(ManifestacionEnLinea.ControlFolios.FolioResp AgregarLevantamientoResult) {
            this.AgregarLevantamientoResult = AgregarLevantamientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPlanoCertificadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPlanoCertificado", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequestBody Body;
        
        public AgregarPlanoCertificadoRequest() {
        }
        
        public AgregarPlanoCertificadoRequest(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPlanoCertificadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarPlanoCertificadoRequestBody() {
        }
        
        public AgregarPlanoCertificadoRequestBody(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPlanoCertificadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPlanoCertificadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponseBody Body;
        
        public AgregarPlanoCertificadoResponse() {
        }
        
        public AgregarPlanoCertificadoResponse(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPlanoCertificadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarPlanoCertificadoResult;
        
        public AgregarPlanoCertificadoResponseBody() {
        }
        
        public AgregarPlanoCertificadoResponseBody(ManifestacionEnLinea.ControlFolios.FolioResp AgregarPlanoCertificadoResult) {
            this.AgregarPlanoCertificadoResult = AgregarPlanoCertificadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatastroControlFoliosSoapChannel : ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatastroControlFoliosSoapClient : System.ServiceModel.ClientBase<ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap>, ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap {
        
        public CatastroControlFoliosSoapClient() {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatastroControlFoliosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.MarcarComoTerminadoPorFolioSIC(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest request) {
            return base.Channel.MarcarComoTerminadoPorFolioSIC(request);
        }
        
        public string MarcarComoTerminadoPorFolioSIC(string clave, string folio_SIC, string folio_SIC_mani) {
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest inValue = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folio_SIC = folio_SIC;
            inValue.Body.folio_SIC_mani = folio_SIC_mani;
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoPorFolioSIC(inValue);
            return retVal.Body.MarcarComoTerminadoPorFolioSICResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.MarcarComoTerminadoPorFolioSICAsync(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest request) {
            return base.Channel.MarcarComoTerminadoPorFolioSICAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICResponse> MarcarComoTerminadoPorFolioSICAsync(string clave, string folio_SIC, string folio_SIC_mani) {
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest inValue = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoPorFolioSICRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folio_SIC = folio_SIC;
            inValue.Body.folio_SIC_mani = folio_SIC_mani;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoPorFolioSICAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.MarcarComoTerminado(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest request) {
            return base.Channel.MarcarComoTerminado(request);
        }
        
        public string MarcarComoTerminado(string clave, string folioSIC) {
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest inValue = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folioSIC = folioSIC;
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).MarcarComoTerminado(inValue);
            return retVal.Body.MarcarComoTerminadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.MarcarComoTerminadoAsync(ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest request) {
            return base.Channel.MarcarComoTerminadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoResponse> MarcarComoTerminadoAsync(string clave, string folioSIC) {
            ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest inValue = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.MarcarComoTerminadoRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folioSIC = folioSIC;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.AgregarFolioResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarFolio(ManifestacionEnLinea.ControlFolios.AgregarFolioRequest request) {
            return base.Channel.AgregarFolio(request);
        }
        
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolio(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarFolioRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarFolioRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarFolioRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlFolios.AgregarFolioResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarFolio(inValue);
            return retVal.Body.AgregarFolioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarFolioAsync(ManifestacionEnLinea.ControlFolios.AgregarFolioRequest request) {
            return base.Channel.AgregarFolioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioResponse> AgregarFolioAsync(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarFolioRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarFolioRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarFolioRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarFolioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest request) {
            return base.Channel.AgregarFolioAvaluoCatastral(request);
        }
        
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarFolioAvaluoCatastral(inValue);
            return retVal.Body.AgregarFolioAvaluoCatastralResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest request) {
            return base.Channel.AgregarFolioAvaluoCatastralAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralResponse> AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarFolioAvaluoCatastralRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarFolioAvaluoCatastralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarLevantamiento(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest request) {
            return base.Channel.AgregarLevantamiento(request);
        }
        
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarLevantamiento(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarLevantamiento(inValue);
            return retVal.Body.AgregarLevantamientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarLevantamientoAsync(ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest request) {
            return base.Channel.AgregarLevantamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarLevantamientoResponse> AgregarLevantamientoAsync(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarLevantamientoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarLevantamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarPlanoCertificado(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest request) {
            return base.Channel.AgregarPlanoCertificado(request);
        }
        
        public ManifestacionEnLinea.ControlFolios.FolioResp AgregarPlanoCertificado(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse retVal = ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarPlanoCertificado(inValue);
            return retVal.Body.AgregarPlanoCertificadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse> ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap.AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest request) {
            return base.Channel.AgregarPlanoCertificadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoResponse> AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlFolios.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest inValue = new ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlFolios.AgregarPlanoCertificadoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlFolios.CatastroControlFoliosSoap)(this)).AgregarPlanoCertificadoAsync(inValue);
        }
    }
}
