//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.WS_Expediente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", ConfigurationName="WS_Expediente.WSExpedienteSoap")]
    public interface WSExpedienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/GetDataByCatPadron", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetDataByCatPadron(string Clave_Unica, string token, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/GetDataByCatPadron", ReplyAction="*")]
        System.Threading.Tasks.Task GetDataByCatPadronAsync(string Clave_Unica, string token, string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ws_ExpedienteConsulta(int tipo_persona, string Identidad, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task Ws_ExpedienteConsultaAsync(int tipo_persona, string Identidad, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaIdTramite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ws_ExpedienteConsultaIdTramite(int tipo_persona, string Identidad, int IdTramite, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaIdTramite", ReplyAction="*")]
        System.Threading.Tasks.Task Ws_ExpedienteConsultaIdTramiteAsync(int tipo_persona, string Identidad, int IdTramite, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ws_ExpedienteConsultaDocumento(int tipodocumento, string metadato, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task Ws_ExpedienteConsultaDocumentoAsync(int tipodocumento, string metadato, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaFolio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ws_ExpedienteConsultaFolio(int tipo_persona, string Identidad, string Folio, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteConsultaFolio", ReplyAction="*")]
        System.Threading.Tasks.Task Ws_ExpedienteConsultaFolioAsync(int tipo_persona, string Identidad, string Folio, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_CiudadanoLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_CiudadanoLogin(string usr, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_CiudadanoLogin", ReplyAction="*")]
        System.Threading.Tasks.Task WS_CiudadanoLoginAsync(string usr, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoActivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteCorreoActivar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoActivar", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteCorreoActivarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoEnviar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteCorreoEnviar(string Titulo, string Contenido, string para, string copia, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoEnviar", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteCorreoEnviarAsync(string Titulo, string Contenido, string para, string copia, string token);
        
        // CODEGEN: El parámetro 'Adjunto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoEnviarAdjunto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse WS_ExpedienteCorreoEnviarAdjunto(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoEnviarAdjunto", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse> WS_ExpedienteCorreoEnviarAdjuntoAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoRecuperar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteCorreoRecuperar(string Identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoRecuperar", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteCorreoRecuperarAsync(string Identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoRestablecer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteCorreoRestablecer(string Identidad, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteCorreoRestablecer", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteCorreoRestablecerAsync(string Identidad, string correo);
        
        // CODEGEN: El parámetro 'archivo' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse WS_ExpedienteSubir(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubir", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse> WS_ExpedienteSubirAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubir64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteSubir64(int Tipopersona, string Identidad, string token, int IdDocumento, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubir64", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteSubir64Async(int Tipopersona, string Identidad, string token, int IdDocumento, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato);
        
        // CODEGEN: El parámetro 'archivo' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubirTramite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse WS_ExpedienteSubirTramite(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubirTramite", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse> WS_ExpedienteSubirTramiteAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubirTramite64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteSubirTramite64(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteSubirTramite64", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteSubirTramite64Async(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteValidaDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteValidaDocumento(int Tipopersona, string Identidad, string token, int IdArchivo, string Expedicion, string Folio, int Validado, string Revisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteValidaDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteValidaDocumentoAsync(int Tipopersona, string Identidad, string token, int IdArchivo, string Expedicion, string Folio, int Validado, string Revisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRespuesta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteTramiteRespuesta(int Tipopersona, string Identidad, string token, int Tramite, string Respuesta, int Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRespuesta", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteTramiteRespuestaAsync(int Tipopersona, string Identidad, string token, int Tramite, string Respuesta, int Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRequisitos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteTramiteRequisitos(int IdApoyo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRequisitos", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteTramiteRequisitosAsync(int IdApoyo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRegistro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteTramiteRegistro(int Tipopersona, string Identidad, string token, int IdDep, int IdApoyo, string Solicitud, string Respuesta, int Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramiteRegistro", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteTramiteRegistroAsync(int Tipopersona, string Identidad, string token, int IdDep, int IdApoyo, string Solicitud, string Respuesta, int Estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteRegistro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteRegistro(
                    int Tipopersona, 
                    string idNacionalidad, 
                    int idDiscapacidad, 
                    string Nombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    string RFC, 
                    string CURP, 
                    string fechaNacimiento, 
                    string idlugarNacimiento, 
                    string idSexo, 
                    string idEstadoCivil, 
                    string razonSocial, 
                    string nombreComercial, 
                    string representanteLegal, 
                    string fechaContitucion, 
                    string idEstado, 
                    string idMunicipio, 
                    string idLocalidad, 
                    string colonia, 
                    string calle, 
                    string nEXterior, 
                    string nInterior, 
                    string codigoPostal, 
                    string telefono, 
                    string celular, 
                    string correoElectronico, 
                    string contrasenia, 
                    string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteRegistro", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteRegistroAsync(
                    int Tipopersona, 
                    string idNacionalidad, 
                    int idDiscapacidad, 
                    string Nombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    string RFC, 
                    string CURP, 
                    string fechaNacimiento, 
                    string idlugarNacimiento, 
                    string idSexo, 
                    string idEstadoCivil, 
                    string razonSocial, 
                    string nombreComercial, 
                    string representanteLegal, 
                    string fechaContitucion, 
                    string idEstado, 
                    string idMunicipio, 
                    string idLocalidad, 
                    string colonia, 
                    string calle, 
                    string nEXterior, 
                    string nInterior, 
                    string codigoPostal, 
                    string telefono, 
                    string celular, 
                    string correoElectronico, 
                    string contrasenia, 
                    string token);
        
        // CODEGEN: El parámetro 'archivo' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteFoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse WS_ExpedienteFoto(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteFoto", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse> WS_ExpedienteFotoAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteFoto64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteFoto64(int TipoPersona, string identidad, string archivo64, string extension, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteFoto64", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteFoto64Async(int TipoPersona, string identidad, string archivo64, string extension, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ValidaLicencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ValidaLicencia(string CURP, string Licencia, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ValidaLicencia", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ValidaLicenciaAsync(string CURP, string Licencia, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Estado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Estado();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Estado", ReplyAction="*")]
        System.Threading.Tasks.Task WS_EstadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Municipio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Municipio(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Municipio", ReplyAction="*")]
        System.Threading.Tasks.Task WS_MunicipioAsync(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Localidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Localidad(string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Localidad", ReplyAction="*")]
        System.Threading.Tasks.Task WS_LocalidadAsync(string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Dependencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Dependencia();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Dependencia", ReplyAction="*")]
        System.Threading.Tasks.Task WS_DependenciaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Sexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Sexo();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Sexo", ReplyAction="*")]
        System.Threading.Tasks.Task WS_SexoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Documentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Documentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Documentos", ReplyAction="*")]
        System.Threading.Tasks.Task WS_DocumentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_EstadoCivil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_EstadoCivil();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_EstadoCivil", ReplyAction="*")]
        System.Threading.Tasks.Task WS_EstadoCivilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Nacionalidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Nacionalidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Nacionalidad", ReplyAction="*")]
        System.Threading.Tasks.Task WS_NacionalidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ws_ExpedienteSMS(string Mensaje, string telefono, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/Ws_ExpedienteSMS", ReplyAction="*")]
        System.Threading.Tasks.Task Ws_ExpedienteSMSAsync(string Mensaje, string telefono, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Estatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_Estatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_Estatus", ReplyAction="*")]
        System.Threading.Tasks.Task WS_EstatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteTramites();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteTramites", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteTramitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_WhatsAppSend(string Telefono, string Mensaje, string url, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSend", ReplyAction="*")]
        System.Threading.Tasks.Task WS_WhatsAppSendAsync(string Telefono, string Mensaje, string url, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSendSoluciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_WhatsAppSendSoluciones(string Telefono, string nombre, string wallet, string fileurl, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSendSoluciones", ReplyAction="*")]
        System.Threading.Tasks.Task WS_WhatsAppSendSolucionesAsync(string Telefono, string nombre, string wallet, string fileurl, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSendAdjunto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_WhatsAppSendAdjunto(string Telefono, string mensaje, string portal, string fileurl, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppSendAdjunto", ReplyAction="*")]
        System.Threading.Tasks.Task WS_WhatsAppSendAdjuntoAsync(string Telefono, string mensaje, string portal, string fileurl, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppValida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_WhatsAppValida(string Telefono, string Aplicacion, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_WhatsAppValida", ReplyAction="*")]
        System.Threading.Tasks.Task WS_WhatsAppValidaAsync(string Telefono, string Aplicacion, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteValidaNAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WS_ExpedienteValidaNAT(string ValidationId, string CURP, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/WS_ExpedienteValidaNAT", ReplyAction="*")]
        System.Threading.Tasks.Task WS_ExpedienteValidaNATAsync(string ValidationId, string CURP, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/JsonSEFIPaseCaja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string JsonSEFIPaseCaja(string PaseCaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://expedientedigital.aguascalientes.gob.mx/JsonSEFIPaseCaja", ReplyAction="*")]
        System.Threading.Tasks.Task<string> JsonSEFIPaseCajaAsync(string PaseCaja);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteCorreoEnviarAdjunto", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteCorreoEnviarAdjuntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public string Titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=1)]
        public string Contenido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=2)]
        public string para;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=3)]
        public string copia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Adjunto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=5)]
        public string extension;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=6)]
        public string token;
        
        public WS_ExpedienteCorreoEnviarAdjuntoRequest() {
        }
        
        public WS_ExpedienteCorreoEnviarAdjuntoRequest(string Titulo, string Contenido, string para, string copia, byte[] Adjunto, string extension, string token) {
            this.Titulo = Titulo;
            this.Contenido = Contenido;
            this.para = para;
            this.copia = copia;
            this.Adjunto = Adjunto;
            this.extension = extension;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteCorreoEnviarAdjuntoResponse", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteCorreoEnviarAdjuntoResponse {
        
        public WS_ExpedienteCorreoEnviarAdjuntoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteSubir", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteSubirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public int Tipopersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=1)]
        public string Identidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=2)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=3)]
        public int IdDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=5)]
        public string Expedicion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=6)]
        public bool Validado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=7)]
        public string Revisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=8)]
        public string extencion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=9)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=10)]
        public string metaDato;
        
        public WS_ExpedienteSubirRequest() {
        }
        
        public WS_ExpedienteSubirRequest(int Tipopersona, string Identidad, string token, int IdDocumento, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            this.Tipopersona = Tipopersona;
            this.Identidad = Identidad;
            this.token = token;
            this.IdDocumento = IdDocumento;
            this.archivo = archivo;
            this.Expedicion = Expedicion;
            this.Validado = Validado;
            this.Revisor = Revisor;
            this.extencion = extencion;
            this.folio = folio;
            this.metaDato = metaDato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteSubirResponse", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteSubirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public string WS_ExpedienteSubirResult;
        
        public WS_ExpedienteSubirResponse() {
        }
        
        public WS_ExpedienteSubirResponse(string WS_ExpedienteSubirResult) {
            this.WS_ExpedienteSubirResult = WS_ExpedienteSubirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteSubirTramite", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteSubirTramiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public int Tipopersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=1)]
        public string Identidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=2)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=3)]
        public int IdDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=4)]
        public int IdTramite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=5)]
        public int IdApoyo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=7)]
        public string Expedicion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=8)]
        public bool Validado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=9)]
        public string Revisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=10)]
        public string extencion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=11)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=12)]
        public string metaDato;
        
        public WS_ExpedienteSubirTramiteRequest() {
        }
        
        public WS_ExpedienteSubirTramiteRequest(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            this.Tipopersona = Tipopersona;
            this.Identidad = Identidad;
            this.token = token;
            this.IdDocumento = IdDocumento;
            this.IdTramite = IdTramite;
            this.IdApoyo = IdApoyo;
            this.archivo = archivo;
            this.Expedicion = Expedicion;
            this.Validado = Validado;
            this.Revisor = Revisor;
            this.extencion = extencion;
            this.folio = folio;
            this.metaDato = metaDato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteSubirTramiteResponse", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteSubirTramiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public string WS_ExpedienteSubirTramiteResult;
        
        public WS_ExpedienteSubirTramiteResponse() {
        }
        
        public WS_ExpedienteSubirTramiteResponse(string WS_ExpedienteSubirTramiteResult) {
            this.WS_ExpedienteSubirTramiteResult = WS_ExpedienteSubirTramiteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteFoto", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteFotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public int TipoPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=1)]
        public string identidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=3)]
        public string extension;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=4)]
        public string token;
        
        public WS_ExpedienteFotoRequest() {
        }
        
        public WS_ExpedienteFotoRequest(int TipoPersona, string identidad, byte[] archivo, string extension, string token) {
            this.TipoPersona = TipoPersona;
            this.identidad = identidad;
            this.archivo = archivo;
            this.extension = extension;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_ExpedienteFotoResponse", WrapperNamespace="https://expedientedigital.aguascalientes.gob.mx/", IsWrapped=true)]
    public partial class WS_ExpedienteFotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://expedientedigital.aguascalientes.gob.mx/", Order=0)]
        public string WS_ExpedienteFotoResult;
        
        public WS_ExpedienteFotoResponse() {
        }
        
        public WS_ExpedienteFotoResponse(string WS_ExpedienteFotoResult) {
            this.WS_ExpedienteFotoResult = WS_ExpedienteFotoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSExpedienteSoapChannel : ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSExpedienteSoapClient : System.ServiceModel.ClientBase<ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap>, ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap {
        
        public WSExpedienteSoapClient() {
        }
        
        public WSExpedienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSExpedienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSExpedienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSExpedienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDataByCatPadron(string Clave_Unica, string token, string Usuario) {
            base.Channel.GetDataByCatPadron(Clave_Unica, token, Usuario);
        }
        
        public System.Threading.Tasks.Task GetDataByCatPadronAsync(string Clave_Unica, string token, string Usuario) {
            return base.Channel.GetDataByCatPadronAsync(Clave_Unica, token, Usuario);
        }
        
        public void Ws_ExpedienteConsulta(int tipo_persona, string Identidad, string token) {
            base.Channel.Ws_ExpedienteConsulta(tipo_persona, Identidad, token);
        }
        
        public System.Threading.Tasks.Task Ws_ExpedienteConsultaAsync(int tipo_persona, string Identidad, string token) {
            return base.Channel.Ws_ExpedienteConsultaAsync(tipo_persona, Identidad, token);
        }
        
        public void Ws_ExpedienteConsultaIdTramite(int tipo_persona, string Identidad, int IdTramite, string token) {
            base.Channel.Ws_ExpedienteConsultaIdTramite(tipo_persona, Identidad, IdTramite, token);
        }
        
        public System.Threading.Tasks.Task Ws_ExpedienteConsultaIdTramiteAsync(int tipo_persona, string Identidad, int IdTramite, string token) {
            return base.Channel.Ws_ExpedienteConsultaIdTramiteAsync(tipo_persona, Identidad, IdTramite, token);
        }
        
        public void Ws_ExpedienteConsultaDocumento(int tipodocumento, string metadato, string token) {
            base.Channel.Ws_ExpedienteConsultaDocumento(tipodocumento, metadato, token);
        }
        
        public System.Threading.Tasks.Task Ws_ExpedienteConsultaDocumentoAsync(int tipodocumento, string metadato, string token) {
            return base.Channel.Ws_ExpedienteConsultaDocumentoAsync(tipodocumento, metadato, token);
        }
        
        public void Ws_ExpedienteConsultaFolio(int tipo_persona, string Identidad, string Folio, string token) {
            base.Channel.Ws_ExpedienteConsultaFolio(tipo_persona, Identidad, Folio, token);
        }
        
        public System.Threading.Tasks.Task Ws_ExpedienteConsultaFolioAsync(int tipo_persona, string Identidad, string Folio, string token) {
            return base.Channel.Ws_ExpedienteConsultaFolioAsync(tipo_persona, Identidad, Folio, token);
        }
        
        public void WS_CiudadanoLogin(string usr, string pass) {
            base.Channel.WS_CiudadanoLogin(usr, pass);
        }
        
        public System.Threading.Tasks.Task WS_CiudadanoLoginAsync(string usr, string pass) {
            return base.Channel.WS_CiudadanoLoginAsync(usr, pass);
        }
        
        public void WS_ExpedienteCorreoActivar(string id) {
            base.Channel.WS_ExpedienteCorreoActivar(id);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteCorreoActivarAsync(string id) {
            return base.Channel.WS_ExpedienteCorreoActivarAsync(id);
        }
        
        public void WS_ExpedienteCorreoEnviar(string Titulo, string Contenido, string para, string copia, string token) {
            base.Channel.WS_ExpedienteCorreoEnviar(Titulo, Contenido, para, copia, token);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteCorreoEnviarAsync(string Titulo, string Contenido, string para, string copia, string token) {
            return base.Channel.WS_ExpedienteCorreoEnviarAsync(Titulo, Contenido, para, copia, token);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteCorreoEnviarAdjunto(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest request) {
            return base.Channel.WS_ExpedienteCorreoEnviarAdjunto(request);
        }
        
        public void WS_ExpedienteCorreoEnviarAdjunto(string Titulo, string Contenido, string para, string copia, byte[] Adjunto, string extension, string token) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest();
            inValue.Titulo = Titulo;
            inValue.Contenido = Contenido;
            inValue.para = para;
            inValue.copia = copia;
            inValue.Adjunto = Adjunto;
            inValue.extension = extension;
            inValue.token = token;
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse retVal = ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteCorreoEnviarAdjunto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse> ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteCorreoEnviarAdjuntoAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest request) {
            return base.Channel.WS_ExpedienteCorreoEnviarAdjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoResponse> WS_ExpedienteCorreoEnviarAdjuntoAsync(string Titulo, string Contenido, string para, string copia, byte[] Adjunto, string extension, string token) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteCorreoEnviarAdjuntoRequest();
            inValue.Titulo = Titulo;
            inValue.Contenido = Contenido;
            inValue.para = para;
            inValue.copia = copia;
            inValue.Adjunto = Adjunto;
            inValue.extension = extension;
            inValue.token = token;
            return ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteCorreoEnviarAdjuntoAsync(inValue);
        }
        
        public void WS_ExpedienteCorreoRecuperar(string Identidad) {
            base.Channel.WS_ExpedienteCorreoRecuperar(Identidad);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteCorreoRecuperarAsync(string Identidad) {
            return base.Channel.WS_ExpedienteCorreoRecuperarAsync(Identidad);
        }
        
        public void WS_ExpedienteCorreoRestablecer(string Identidad, string correo) {
            base.Channel.WS_ExpedienteCorreoRestablecer(Identidad, correo);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteCorreoRestablecerAsync(string Identidad, string correo) {
            return base.Channel.WS_ExpedienteCorreoRestablecerAsync(Identidad, correo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteSubir(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest request) {
            return base.Channel.WS_ExpedienteSubir(request);
        }
        
        public string WS_ExpedienteSubir(int Tipopersona, string Identidad, string token, int IdDocumento, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest();
            inValue.Tipopersona = Tipopersona;
            inValue.Identidad = Identidad;
            inValue.token = token;
            inValue.IdDocumento = IdDocumento;
            inValue.archivo = archivo;
            inValue.Expedicion = Expedicion;
            inValue.Validado = Validado;
            inValue.Revisor = Revisor;
            inValue.extencion = extencion;
            inValue.folio = folio;
            inValue.metaDato = metaDato;
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse retVal = ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteSubir(inValue);
            return retVal.WS_ExpedienteSubirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse> ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteSubirAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest request) {
            return base.Channel.WS_ExpedienteSubirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirResponse> WS_ExpedienteSubirAsync(int Tipopersona, string Identidad, string token, int IdDocumento, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirRequest();
            inValue.Tipopersona = Tipopersona;
            inValue.Identidad = Identidad;
            inValue.token = token;
            inValue.IdDocumento = IdDocumento;
            inValue.archivo = archivo;
            inValue.Expedicion = Expedicion;
            inValue.Validado = Validado;
            inValue.Revisor = Revisor;
            inValue.extencion = extencion;
            inValue.folio = folio;
            inValue.metaDato = metaDato;
            return ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteSubirAsync(inValue);
        }
        
        public void WS_ExpedienteSubir64(int Tipopersona, string Identidad, string token, int IdDocumento, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            base.Channel.WS_ExpedienteSubir64(Tipopersona, Identidad, token, IdDocumento, archivo64, Expedicion, Validado, Revisor, extencion, folio, metaDato);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteSubir64Async(int Tipopersona, string Identidad, string token, int IdDocumento, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            return base.Channel.WS_ExpedienteSubir64Async(Tipopersona, Identidad, token, IdDocumento, archivo64, Expedicion, Validado, Revisor, extencion, folio, metaDato);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteSubirTramite(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest request) {
            return base.Channel.WS_ExpedienteSubirTramite(request);
        }
        
        public string WS_ExpedienteSubirTramite(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest();
            inValue.Tipopersona = Tipopersona;
            inValue.Identidad = Identidad;
            inValue.token = token;
            inValue.IdDocumento = IdDocumento;
            inValue.IdTramite = IdTramite;
            inValue.IdApoyo = IdApoyo;
            inValue.archivo = archivo;
            inValue.Expedicion = Expedicion;
            inValue.Validado = Validado;
            inValue.Revisor = Revisor;
            inValue.extencion = extencion;
            inValue.folio = folio;
            inValue.metaDato = metaDato;
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse retVal = ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteSubirTramite(inValue);
            return retVal.WS_ExpedienteSubirTramiteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse> ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteSubirTramiteAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest request) {
            return base.Channel.WS_ExpedienteSubirTramiteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteResponse> WS_ExpedienteSubirTramiteAsync(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, byte[] archivo, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteSubirTramiteRequest();
            inValue.Tipopersona = Tipopersona;
            inValue.Identidad = Identidad;
            inValue.token = token;
            inValue.IdDocumento = IdDocumento;
            inValue.IdTramite = IdTramite;
            inValue.IdApoyo = IdApoyo;
            inValue.archivo = archivo;
            inValue.Expedicion = Expedicion;
            inValue.Validado = Validado;
            inValue.Revisor = Revisor;
            inValue.extencion = extencion;
            inValue.folio = folio;
            inValue.metaDato = metaDato;
            return ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteSubirTramiteAsync(inValue);
        }
        
        public void WS_ExpedienteSubirTramite64(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            base.Channel.WS_ExpedienteSubirTramite64(Tipopersona, Identidad, token, IdDocumento, IdTramite, IdApoyo, archivo64, Expedicion, Validado, Revisor, extencion, folio, metaDato);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteSubirTramite64Async(int Tipopersona, string Identidad, string token, int IdDocumento, int IdTramite, int IdApoyo, string archivo64, string Expedicion, bool Validado, string Revisor, string extencion, string folio, string metaDato) {
            return base.Channel.WS_ExpedienteSubirTramite64Async(Tipopersona, Identidad, token, IdDocumento, IdTramite, IdApoyo, archivo64, Expedicion, Validado, Revisor, extencion, folio, metaDato);
        }
        
        public void WS_ExpedienteValidaDocumento(int Tipopersona, string Identidad, string token, int IdArchivo, string Expedicion, string Folio, int Validado, string Revisor) {
            base.Channel.WS_ExpedienteValidaDocumento(Tipopersona, Identidad, token, IdArchivo, Expedicion, Folio, Validado, Revisor);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteValidaDocumentoAsync(int Tipopersona, string Identidad, string token, int IdArchivo, string Expedicion, string Folio, int Validado, string Revisor) {
            return base.Channel.WS_ExpedienteValidaDocumentoAsync(Tipopersona, Identidad, token, IdArchivo, Expedicion, Folio, Validado, Revisor);
        }
        
        public void WS_ExpedienteTramiteRespuesta(int Tipopersona, string Identidad, string token, int Tramite, string Respuesta, int Estatus) {
            base.Channel.WS_ExpedienteTramiteRespuesta(Tipopersona, Identidad, token, Tramite, Respuesta, Estatus);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteTramiteRespuestaAsync(int Tipopersona, string Identidad, string token, int Tramite, string Respuesta, int Estatus) {
            return base.Channel.WS_ExpedienteTramiteRespuestaAsync(Tipopersona, Identidad, token, Tramite, Respuesta, Estatus);
        }
        
        public void WS_ExpedienteTramiteRequisitos(int IdApoyo) {
            base.Channel.WS_ExpedienteTramiteRequisitos(IdApoyo);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteTramiteRequisitosAsync(int IdApoyo) {
            return base.Channel.WS_ExpedienteTramiteRequisitosAsync(IdApoyo);
        }
        
        public void WS_ExpedienteTramiteRegistro(int Tipopersona, string Identidad, string token, int IdDep, int IdApoyo, string Solicitud, string Respuesta, int Estatus) {
            base.Channel.WS_ExpedienteTramiteRegistro(Tipopersona, Identidad, token, IdDep, IdApoyo, Solicitud, Respuesta, Estatus);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteTramiteRegistroAsync(int Tipopersona, string Identidad, string token, int IdDep, int IdApoyo, string Solicitud, string Respuesta, int Estatus) {
            return base.Channel.WS_ExpedienteTramiteRegistroAsync(Tipopersona, Identidad, token, IdDep, IdApoyo, Solicitud, Respuesta, Estatus);
        }
        
        public void WS_ExpedienteRegistro(
                    int Tipopersona, 
                    string idNacionalidad, 
                    int idDiscapacidad, 
                    string Nombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    string RFC, 
                    string CURP, 
                    string fechaNacimiento, 
                    string idlugarNacimiento, 
                    string idSexo, 
                    string idEstadoCivil, 
                    string razonSocial, 
                    string nombreComercial, 
                    string representanteLegal, 
                    string fechaContitucion, 
                    string idEstado, 
                    string idMunicipio, 
                    string idLocalidad, 
                    string colonia, 
                    string calle, 
                    string nEXterior, 
                    string nInterior, 
                    string codigoPostal, 
                    string telefono, 
                    string celular, 
                    string correoElectronico, 
                    string contrasenia, 
                    string token) {
            base.Channel.WS_ExpedienteRegistro(Tipopersona, idNacionalidad, idDiscapacidad, Nombre, PrimerApellido, SegundoApellido, RFC, CURP, fechaNacimiento, idlugarNacimiento, idSexo, idEstadoCivil, razonSocial, nombreComercial, representanteLegal, fechaContitucion, idEstado, idMunicipio, idLocalidad, colonia, calle, nEXterior, nInterior, codigoPostal, telefono, celular, correoElectronico, contrasenia, token);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteRegistroAsync(
                    int Tipopersona, 
                    string idNacionalidad, 
                    int idDiscapacidad, 
                    string Nombre, 
                    string PrimerApellido, 
                    string SegundoApellido, 
                    string RFC, 
                    string CURP, 
                    string fechaNacimiento, 
                    string idlugarNacimiento, 
                    string idSexo, 
                    string idEstadoCivil, 
                    string razonSocial, 
                    string nombreComercial, 
                    string representanteLegal, 
                    string fechaContitucion, 
                    string idEstado, 
                    string idMunicipio, 
                    string idLocalidad, 
                    string colonia, 
                    string calle, 
                    string nEXterior, 
                    string nInterior, 
                    string codigoPostal, 
                    string telefono, 
                    string celular, 
                    string correoElectronico, 
                    string contrasenia, 
                    string token) {
            return base.Channel.WS_ExpedienteRegistroAsync(Tipopersona, idNacionalidad, idDiscapacidad, Nombre, PrimerApellido, SegundoApellido, RFC, CURP, fechaNacimiento, idlugarNacimiento, idSexo, idEstadoCivil, razonSocial, nombreComercial, representanteLegal, fechaContitucion, idEstado, idMunicipio, idLocalidad, colonia, calle, nEXterior, nInterior, codigoPostal, telefono, celular, correoElectronico, contrasenia, token);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteFoto(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest request) {
            return base.Channel.WS_ExpedienteFoto(request);
        }
        
        public string WS_ExpedienteFoto(int TipoPersona, string identidad, byte[] archivo, string extension, string token) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest();
            inValue.TipoPersona = TipoPersona;
            inValue.identidad = identidad;
            inValue.archivo = archivo;
            inValue.extension = extension;
            inValue.token = token;
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse retVal = ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteFoto(inValue);
            return retVal.WS_ExpedienteFotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse> ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap.WS_ExpedienteFotoAsync(ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest request) {
            return base.Channel.WS_ExpedienteFotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoResponse> WS_ExpedienteFotoAsync(int TipoPersona, string identidad, byte[] archivo, string extension, string token) {
            ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest inValue = new ManifestacionEnLinea.WS_Expediente.WS_ExpedienteFotoRequest();
            inValue.TipoPersona = TipoPersona;
            inValue.identidad = identidad;
            inValue.archivo = archivo;
            inValue.extension = extension;
            inValue.token = token;
            return ((ManifestacionEnLinea.WS_Expediente.WSExpedienteSoap)(this)).WS_ExpedienteFotoAsync(inValue);
        }
        
        public void WS_ExpedienteFoto64(int TipoPersona, string identidad, string archivo64, string extension, string token) {
            base.Channel.WS_ExpedienteFoto64(TipoPersona, identidad, archivo64, extension, token);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteFoto64Async(int TipoPersona, string identidad, string archivo64, string extension, string token) {
            return base.Channel.WS_ExpedienteFoto64Async(TipoPersona, identidad, archivo64, extension, token);
        }
        
        public void WS_ValidaLicencia(string CURP, string Licencia, string duracion) {
            base.Channel.WS_ValidaLicencia(CURP, Licencia, duracion);
        }
        
        public System.Threading.Tasks.Task WS_ValidaLicenciaAsync(string CURP, string Licencia, string duracion) {
            return base.Channel.WS_ValidaLicenciaAsync(CURP, Licencia, duracion);
        }
        
        public void WS_Estado() {
            base.Channel.WS_Estado();
        }
        
        public System.Threading.Tasks.Task WS_EstadoAsync() {
            return base.Channel.WS_EstadoAsync();
        }
        
        public void WS_Municipio(string estado) {
            base.Channel.WS_Municipio(estado);
        }
        
        public System.Threading.Tasks.Task WS_MunicipioAsync(string estado) {
            return base.Channel.WS_MunicipioAsync(estado);
        }
        
        public void WS_Localidad(string estado, string municipio) {
            base.Channel.WS_Localidad(estado, municipio);
        }
        
        public System.Threading.Tasks.Task WS_LocalidadAsync(string estado, string municipio) {
            return base.Channel.WS_LocalidadAsync(estado, municipio);
        }
        
        public void WS_Dependencia() {
            base.Channel.WS_Dependencia();
        }
        
        public System.Threading.Tasks.Task WS_DependenciaAsync() {
            return base.Channel.WS_DependenciaAsync();
        }
        
        public void WS_Sexo() {
            base.Channel.WS_Sexo();
        }
        
        public System.Threading.Tasks.Task WS_SexoAsync() {
            return base.Channel.WS_SexoAsync();
        }
        
        public void WS_Documentos() {
            base.Channel.WS_Documentos();
        }
        
        public System.Threading.Tasks.Task WS_DocumentosAsync() {
            return base.Channel.WS_DocumentosAsync();
        }
        
        public void WS_EstadoCivil() {
            base.Channel.WS_EstadoCivil();
        }
        
        public System.Threading.Tasks.Task WS_EstadoCivilAsync() {
            return base.Channel.WS_EstadoCivilAsync();
        }
        
        public void WS_Nacionalidad() {
            base.Channel.WS_Nacionalidad();
        }
        
        public System.Threading.Tasks.Task WS_NacionalidadAsync() {
            return base.Channel.WS_NacionalidadAsync();
        }
        
        public void Ws_ExpedienteSMS(string Mensaje, string telefono, string token) {
            base.Channel.Ws_ExpedienteSMS(Mensaje, telefono, token);
        }
        
        public System.Threading.Tasks.Task Ws_ExpedienteSMSAsync(string Mensaje, string telefono, string token) {
            return base.Channel.Ws_ExpedienteSMSAsync(Mensaje, telefono, token);
        }
        
        public void WS_Estatus() {
            base.Channel.WS_Estatus();
        }
        
        public System.Threading.Tasks.Task WS_EstatusAsync() {
            return base.Channel.WS_EstatusAsync();
        }
        
        public void WS_ExpedienteTramites() {
            base.Channel.WS_ExpedienteTramites();
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteTramitesAsync() {
            return base.Channel.WS_ExpedienteTramitesAsync();
        }
        
        public void WS_WhatsAppSend(string Telefono, string Mensaje, string url, string token) {
            base.Channel.WS_WhatsAppSend(Telefono, Mensaje, url, token);
        }
        
        public System.Threading.Tasks.Task WS_WhatsAppSendAsync(string Telefono, string Mensaje, string url, string token) {
            return base.Channel.WS_WhatsAppSendAsync(Telefono, Mensaje, url, token);
        }
        
        public void WS_WhatsAppSendSoluciones(string Telefono, string nombre, string wallet, string fileurl, string token) {
            base.Channel.WS_WhatsAppSendSoluciones(Telefono, nombre, wallet, fileurl, token);
        }
        
        public System.Threading.Tasks.Task WS_WhatsAppSendSolucionesAsync(string Telefono, string nombre, string wallet, string fileurl, string token) {
            return base.Channel.WS_WhatsAppSendSolucionesAsync(Telefono, nombre, wallet, fileurl, token);
        }
        
        public void WS_WhatsAppSendAdjunto(string Telefono, string mensaje, string portal, string fileurl, string token) {
            base.Channel.WS_WhatsAppSendAdjunto(Telefono, mensaje, portal, fileurl, token);
        }
        
        public System.Threading.Tasks.Task WS_WhatsAppSendAdjuntoAsync(string Telefono, string mensaje, string portal, string fileurl, string token) {
            return base.Channel.WS_WhatsAppSendAdjuntoAsync(Telefono, mensaje, portal, fileurl, token);
        }
        
        public void WS_WhatsAppValida(string Telefono, string Aplicacion, string token) {
            base.Channel.WS_WhatsAppValida(Telefono, Aplicacion, token);
        }
        
        public System.Threading.Tasks.Task WS_WhatsAppValidaAsync(string Telefono, string Aplicacion, string token) {
            return base.Channel.WS_WhatsAppValidaAsync(Telefono, Aplicacion, token);
        }
        
        public void WS_ExpedienteValidaNAT(string ValidationId, string CURP, string token) {
            base.Channel.WS_ExpedienteValidaNAT(ValidationId, CURP, token);
        }
        
        public System.Threading.Tasks.Task WS_ExpedienteValidaNATAsync(string ValidationId, string CURP, string token) {
            return base.Channel.WS_ExpedienteValidaNATAsync(ValidationId, CURP, token);
        }
        
        public string JsonSEFIPaseCaja(string PaseCaja) {
            return base.Channel.JsonSEFIPaseCaja(PaseCaja);
        }
        
        public System.Threading.Tasks.Task<string> JsonSEFIPaseCajaAsync(string PaseCaja) {
            return base.Channel.JsonSEFIPaseCajaAsync(PaseCaja);
        }
    }
}
