//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.DeclaracionPagos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", ConfigurationName="DeclaracionPagos.SDeclaracionSoap")]
    public interface SDeclaracionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento validaDeclaracionResult del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracion", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse validaDeclaracion(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracion", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse> validaDeclaracionAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento referencia del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferencia", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse validaDeclaracionReferencia(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse> validaDeclaracionReferenciaAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento referencia del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaR" +
            "egCivil", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse validaDeclaracionReferenciaRegCivil(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaR" +
            "egCivil", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse> validaDeclaracionReferenciaRegCivilAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento referencia del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaR" +
            "PP", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse validaDeclaracionReferenciaRPP(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaR" +
            "PP", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse> validaDeclaracionReferenciaRPPAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento referencia del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaP" +
            "ROESPA", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse validaDeclaracionReferenciaPROESPA(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/validaDeclaracionReferenciaP" +
            "ROESPA", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse> validaDeclaracionReferenciaPROESPAAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cie del espacio de nombres https://eservicios2.aguascalientes.gob.mx/WsIngresos/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/costoCIE", ReplyAction="*")]
        ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse costoCIE(ManifestacionEnLinea.DeclaracionPagos.costoCIERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://eservicios2.aguascalientes.gob.mx/WsIngresos/costoCIE", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse> costoCIEAsync(ManifestacionEnLinea.DeclaracionPagos.costoCIERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracion", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequestBody Body;
        
        public validaDeclaracionRequest() {
        }
        
        public validaDeclaracionRequest(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int declaracion;
        
        public validaDeclaracionRequestBody() {
        }
        
        public validaDeclaracionRequestBody(int declaracion) {
            this.declaracion = declaracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponseBody Body;
        
        public validaDeclaracionResponse() {
        }
        
        public validaDeclaracionResponse(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validaDeclaracionResult;
        
        public validaDeclaracionResponseBody() {
        }
        
        public validaDeclaracionResponseBody(string validaDeclaracionResult) {
            this.validaDeclaracionResult = validaDeclaracionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferencia", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequestBody Body;
        
        public validaDeclaracionReferenciaRequest() {
        }
        
        public validaDeclaracionReferenciaRequest(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referencia;
        
        public validaDeclaracionReferenciaRequestBody() {
        }
        
        public validaDeclaracionReferenciaRequestBody(string referencia) {
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponseBody Body;
        
        public validaDeclaracionReferenciaResponse() {
        }
        
        public validaDeclaracionReferenciaResponse(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validaDeclaracionReferenciaResult;
        
        public validaDeclaracionReferenciaResponseBody() {
        }
        
        public validaDeclaracionReferenciaResponseBody(string validaDeclaracionReferenciaResult) {
            this.validaDeclaracionReferenciaResult = validaDeclaracionReferenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaRegCivilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaRegCivil", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequestBody Body;
        
        public validaDeclaracionReferenciaRegCivilRequest() {
        }
        
        public validaDeclaracionReferenciaRegCivilRequest(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaRegCivilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referencia;
        
        public validaDeclaracionReferenciaRegCivilRequestBody() {
        }
        
        public validaDeclaracionReferenciaRegCivilRequestBody(string referencia) {
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaRegCivilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaRegCivilResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponseBody Body;
        
        public validaDeclaracionReferenciaRegCivilResponse() {
        }
        
        public validaDeclaracionReferenciaRegCivilResponse(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaRegCivilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validaDeclaracionReferenciaRegCivilResult;
        
        public validaDeclaracionReferenciaRegCivilResponseBody() {
        }
        
        public validaDeclaracionReferenciaRegCivilResponseBody(string validaDeclaracionReferenciaRegCivilResult) {
            this.validaDeclaracionReferenciaRegCivilResult = validaDeclaracionReferenciaRegCivilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaRPPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaRPP", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequestBody Body;
        
        public validaDeclaracionReferenciaRPPRequest() {
        }
        
        public validaDeclaracionReferenciaRPPRequest(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaRPPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referencia;
        
        public validaDeclaracionReferenciaRPPRequestBody() {
        }
        
        public validaDeclaracionReferenciaRPPRequestBody(string referencia) {
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaRPPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaRPPResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponseBody Body;
        
        public validaDeclaracionReferenciaRPPResponse() {
        }
        
        public validaDeclaracionReferenciaRPPResponse(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaRPPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement validaDeclaracionReferenciaRPPResult;
        
        public validaDeclaracionReferenciaRPPResponseBody() {
        }
        
        public validaDeclaracionReferenciaRPPResponseBody(System.Xml.Linq.XElement validaDeclaracionReferenciaRPPResult) {
            this.validaDeclaracionReferenciaRPPResult = validaDeclaracionReferenciaRPPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaPROESPARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaPROESPA", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequestBody Body;
        
        public validaDeclaracionReferenciaPROESPARequest() {
        }
        
        public validaDeclaracionReferenciaPROESPARequest(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaPROESPARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string referencia;
        
        public validaDeclaracionReferenciaPROESPARequestBody() {
        }
        
        public validaDeclaracionReferenciaPROESPARequestBody(string referencia) {
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaDeclaracionReferenciaPROESPAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaDeclaracionReferenciaPROESPAResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponseBody Body;
        
        public validaDeclaracionReferenciaPROESPAResponse() {
        }
        
        public validaDeclaracionReferenciaPROESPAResponse(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class validaDeclaracionReferenciaPROESPAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement validaDeclaracionReferenciaPROESPAResult;
        
        public validaDeclaracionReferenciaPROESPAResponseBody() {
        }
        
        public validaDeclaracionReferenciaPROESPAResponseBody(System.Xml.Linq.XElement validaDeclaracionReferenciaPROESPAResult) {
            this.validaDeclaracionReferenciaPROESPAResult = validaDeclaracionReferenciaPROESPAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costoCIERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costoCIE", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.costoCIERequestBody Body;
        
        public costoCIERequest() {
        }
        
        public costoCIERequest(ManifestacionEnLinea.DeclaracionPagos.costoCIERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class costoCIERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cie;
        
        public costoCIERequestBody() {
        }
        
        public costoCIERequestBody(string cie) {
            this.cie = cie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class costoCIEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="costoCIEResponse", Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/", Order=0)]
        public ManifestacionEnLinea.DeclaracionPagos.costoCIEResponseBody Body;
        
        public costoCIEResponse() {
        }
        
        public costoCIEResponse(ManifestacionEnLinea.DeclaracionPagos.costoCIEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://eservicios2.aguascalientes.gob.mx/WsIngresos/")]
    public partial class costoCIEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string costoCIEResult;
        
        public costoCIEResponseBody() {
        }
        
        public costoCIEResponseBody(string costoCIEResult) {
            this.costoCIEResult = costoCIEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDeclaracionSoapChannel : ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDeclaracionSoapClient : System.ServiceModel.ClientBase<ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap>, ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap {
        
        public SDeclaracionSoapClient() {
        }
        
        public SDeclaracionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDeclaracionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDeclaracionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDeclaracionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracion(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest request) {
            return base.Channel.validaDeclaracion(request);
        }
        
        public string validaDeclaracion(int declaracion) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequestBody();
            inValue.Body.declaracion = declaracion;
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracion(inValue);
            return retVal.Body.validaDeclaracionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest request) {
            return base.Channel.validaDeclaracionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionResponse> validaDeclaracionAsync(int declaracion) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionRequestBody();
            inValue.Body.declaracion = declaracion;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferencia(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest request) {
            return base.Channel.validaDeclaracionReferencia(request);
        }
        
        public string validaDeclaracionReferencia(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequestBody();
            inValue.Body.referencia = referencia;
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferencia(inValue);
            return retVal.Body.validaDeclaracionReferenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest request) {
            return base.Channel.validaDeclaracionReferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaResponse> validaDeclaracionReferenciaAsync(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRequestBody();
            inValue.Body.referencia = referencia;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaRegCivil(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest request) {
            return base.Channel.validaDeclaracionReferenciaRegCivil(request);
        }
        
        public string validaDeclaracionReferenciaRegCivil(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequestBody();
            inValue.Body.referencia = referencia;
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaRegCivil(inValue);
            return retVal.Body.validaDeclaracionReferenciaRegCivilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaRegCivilAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest request) {
            return base.Channel.validaDeclaracionReferenciaRegCivilAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilResponse> validaDeclaracionReferenciaRegCivilAsync(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRegCivilRequestBody();
            inValue.Body.referencia = referencia;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaRegCivilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaRPP(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest request) {
            return base.Channel.validaDeclaracionReferenciaRPP(request);
        }
        
        public System.Xml.Linq.XElement validaDeclaracionReferenciaRPP(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequestBody();
            inValue.Body.referencia = referencia;
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaRPP(inValue);
            return retVal.Body.validaDeclaracionReferenciaRPPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaRPPAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest request) {
            return base.Channel.validaDeclaracionReferenciaRPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPResponse> validaDeclaracionReferenciaRPPAsync(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaRPPRequestBody();
            inValue.Body.referencia = referencia;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaRPPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaPROESPA(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest request) {
            return base.Channel.validaDeclaracionReferenciaPROESPA(request);
        }
        
        public System.Xml.Linq.XElement validaDeclaracionReferenciaPROESPA(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequestBody();
            inValue.Body.referencia = referencia;
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaPROESPA(inValue);
            return retVal.Body.validaDeclaracionReferenciaPROESPAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.validaDeclaracionReferenciaPROESPAAsync(ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest request) {
            return base.Channel.validaDeclaracionReferenciaPROESPAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPAResponse> validaDeclaracionReferenciaPROESPAAsync(string referencia) {
            ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest inValue = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.validaDeclaracionReferenciaPROESPARequestBody();
            inValue.Body.referencia = referencia;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).validaDeclaracionReferenciaPROESPAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.costoCIE(ManifestacionEnLinea.DeclaracionPagos.costoCIERequest request) {
            return base.Channel.costoCIE(request);
        }
        
        public string costoCIE(string cie) {
            ManifestacionEnLinea.DeclaracionPagos.costoCIERequest inValue = new ManifestacionEnLinea.DeclaracionPagos.costoCIERequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.costoCIERequestBody();
            inValue.Body.cie = cie;
            ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse retVal = ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).costoCIE(inValue);
            return retVal.Body.costoCIEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse> ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap.costoCIEAsync(ManifestacionEnLinea.DeclaracionPagos.costoCIERequest request) {
            return base.Channel.costoCIEAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.DeclaracionPagos.costoCIEResponse> costoCIEAsync(string cie) {
            ManifestacionEnLinea.DeclaracionPagos.costoCIERequest inValue = new ManifestacionEnLinea.DeclaracionPagos.costoCIERequest();
            inValue.Body = new ManifestacionEnLinea.DeclaracionPagos.costoCIERequestBody();
            inValue.Body.cie = cie;
            return ((ManifestacionEnLinea.DeclaracionPagos.SDeclaracionSoap)(this)).costoCIEAsync(inValue);
        }
    }
}
