//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestacionEnLinea.ControlDeFolioDesa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioSolicitud", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FolioSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folio_SICField;
        
        private System.Nullable<bool> mani_con_avaluoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombreSolicitante {
            get {
                return this.nombreSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreSolicitanteField, value) != true)) {
                    this.nombreSolicitanteField = value;
                    this.RaisePropertyChanged("nombreSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionField, value) != true)) {
                    this.observacionField = value;
                    this.RaisePropertyChanged("observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folio_SIC {
            get {
                return this.folio_SICField;
            }
            set {
                if ((object.ReferenceEquals(this.folio_SICField, value) != true)) {
                    this.folio_SICField = value;
                    this.RaisePropertyChanged("folio_SIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<bool> mani_con_avaluo {
            get {
                return this.mani_con_avaluoField;
            }
            set {
                if ((this.mani_con_avaluoField.Equals(value) != true)) {
                    this.mani_con_avaluoField = value;
                    this.RaisePropertyChanged("mani_con_avaluo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioResp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FolioResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        private int id_folioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_folio {
            get {
                return this.id_folioField;
            }
            set {
                if ((this.id_folioField.Equals(value) != true)) {
                    this.id_folioField = value;
                    this.RaisePropertyChanged("id_folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string res {
            get {
                return this.resField;
            }
            set {
                if ((object.ReferenceEquals(this.resField, value) != true)) {
                    this.resField = value;
                    this.RaisePropertyChanged("res");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlDeFolioDesa.CatastroControlFoliosSoap")]
    public interface CatastroControlFoliosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse HelloWorld(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse> HelloWorldAsync(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorld2Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response HelloWorld2(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response> HelloWorld2Async(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        int Sumar(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int a, int b);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clave del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminadoPorFolioSIC", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse MarcarComoTerminadoPorFolioSIC(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminadoPorFolioSIC", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse> MarcarComoTerminadoPorFolioSICAsync(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clave del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminado", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse MarcarComoTerminado(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarComoTerminado", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse> MarcarComoTerminadoAsync(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolio", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse AgregarFolio(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolio", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse> AgregarFolioAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolioAvaluoCatastral", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarFolioAvaluoCatastral", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse> AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLevantamiento", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse AgregarLevantamiento(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLevantamiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse> AgregarLevantamientoAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPlanoCertificado", ReplyAction="*")]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse AgregarPlanoCertificado(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPlanoCertificado", ReplyAction="*")]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse> AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2RequestBody Body;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld2RequestBody {
        
        public HelloWorld2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2Response", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2ResponseBody Body;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2ResponseBody() {
        }
        
        public HelloWorld2ResponseBody(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoPorFolioSICRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoPorFolioSIC", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequestBody Body;
        
        public MarcarComoTerminadoPorFolioSICRequest() {
        }
        
        public MarcarComoTerminadoPorFolioSICRequest(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoPorFolioSICRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folio_SIC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string folio_SIC_mani;
        
        public MarcarComoTerminadoPorFolioSICRequestBody() {
        }
        
        public MarcarComoTerminadoPorFolioSICRequestBody(string clave, string folio_SIC, string folio_SIC_mani) {
            this.clave = clave;
            this.folio_SIC = folio_SIC;
            this.folio_SIC_mani = folio_SIC_mani;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoPorFolioSICResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoPorFolioSICResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponseBody Body;
        
        public MarcarComoTerminadoPorFolioSICResponse() {
        }
        
        public MarcarComoTerminadoPorFolioSICResponse(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoPorFolioSICResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarcarComoTerminadoPorFolioSICResult;
        
        public MarcarComoTerminadoPorFolioSICResponseBody() {
        }
        
        public MarcarComoTerminadoPorFolioSICResponseBody(string MarcarComoTerminadoPorFolioSICResult) {
            this.MarcarComoTerminadoPorFolioSICResult = MarcarComoTerminadoPorFolioSICResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminado", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequestBody Body;
        
        public MarcarComoTerminadoRequest() {
        }
        
        public MarcarComoTerminadoRequest(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folioSIC;
        
        public MarcarComoTerminadoRequestBody() {
        }
        
        public MarcarComoTerminadoRequestBody(string clave, string folioSIC) {
            this.clave = clave;
            this.folioSIC = folioSIC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcarComoTerminadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcarComoTerminadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponseBody Body;
        
        public MarcarComoTerminadoResponse() {
        }
        
        public MarcarComoTerminadoResponse(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MarcarComoTerminadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarcarComoTerminadoResult;
        
        public MarcarComoTerminadoResponseBody() {
        }
        
        public MarcarComoTerminadoResponseBody(string MarcarComoTerminadoResult) {
            this.MarcarComoTerminadoResult = MarcarComoTerminadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolio", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequestBody Body;
        
        public AgregarFolioRequest() {
        }
        
        public AgregarFolioRequest(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarFolioRequestBody() {
        }
        
        public AgregarFolioRequestBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponseBody Body;
        
        public AgregarFolioResponse() {
        }
        
        public AgregarFolioResponse(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolioResult;
        
        public AgregarFolioResponseBody() {
        }
        
        public AgregarFolioResponseBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolioResult) {
            this.AgregarFolioResult = AgregarFolioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioAvaluoCatastralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioAvaluoCatastral", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequestBody Body;
        
        public AgregarFolioAvaluoCatastralRequest() {
        }
        
        public AgregarFolioAvaluoCatastralRequest(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioAvaluoCatastralRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarFolioAvaluoCatastralRequestBody() {
        }
        
        public AgregarFolioAvaluoCatastralRequestBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarFolioAvaluoCatastralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarFolioAvaluoCatastralResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponseBody Body;
        
        public AgregarFolioAvaluoCatastralResponse() {
        }
        
        public AgregarFolioAvaluoCatastralResponse(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarFolioAvaluoCatastralResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolioAvaluoCatastralResult;
        
        public AgregarFolioAvaluoCatastralResponseBody() {
        }
        
        public AgregarFolioAvaluoCatastralResponseBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolioAvaluoCatastralResult) {
            this.AgregarFolioAvaluoCatastralResult = AgregarFolioAvaluoCatastralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLevantamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLevantamiento", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequestBody Body;
        
        public AgregarLevantamientoRequest() {
        }
        
        public AgregarLevantamientoRequest(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLevantamientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarLevantamientoRequestBody() {
        }
        
        public AgregarLevantamientoRequestBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLevantamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLevantamientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponseBody Body;
        
        public AgregarLevantamientoResponse() {
        }
        
        public AgregarLevantamientoResponse(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLevantamientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarLevantamientoResult;
        
        public AgregarLevantamientoResponseBody() {
        }
        
        public AgregarLevantamientoResponseBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarLevantamientoResult) {
            this.AgregarLevantamientoResult = AgregarLevantamientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPlanoCertificadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPlanoCertificado", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequestBody Body;
        
        public AgregarPlanoCertificadoRequest() {
        }
        
        public AgregarPlanoCertificadoRequest(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPlanoCertificadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AgregarPlanoCertificadoRequestBody() {
        }
        
        public AgregarPlanoCertificadoRequestBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            this.folio = folio;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPlanoCertificadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPlanoCertificadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponseBody Body;
        
        public AgregarPlanoCertificadoResponse() {
        }
        
        public AgregarPlanoCertificadoResponse(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPlanoCertificadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarPlanoCertificadoResult;
        
        public AgregarPlanoCertificadoResponseBody() {
        }
        
        public AgregarPlanoCertificadoResponseBody(ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarPlanoCertificadoResult) {
            this.AgregarPlanoCertificadoResult = AgregarPlanoCertificadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatastroControlFoliosSoapChannel : ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatastroControlFoliosSoapClient : System.ServiceModel.ClientBase<ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap>, ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap {
        
        public CatastroControlFoliosSoapClient() {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatastroControlFoliosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatastroControlFoliosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.HelloWorld(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequestBody();
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.HelloWorldAsync(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldResponse> HelloWorldAsync() {
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorldRequestBody();
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.HelloWorld2(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request inValue = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2RequestBody();
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).HelloWorld2(inValue);
            return retVal.Body.HelloWorld2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.HelloWorld2Async(ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request request) {
            return base.Channel.HelloWorld2Async(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Response> HelloWorld2Async() {
            ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request inValue = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2Request();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.HelloWorld2RequestBody();
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).HelloWorld2Async(inValue);
        }
        
        public int Sumar(int a, int b) {
            return base.Channel.Sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int a, int b) {
            return base.Channel.SumarAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.MarcarComoTerminadoPorFolioSIC(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest request) {
            return base.Channel.MarcarComoTerminadoPorFolioSIC(request);
        }
        
        public string MarcarComoTerminadoPorFolioSIC(string clave, string folio_SIC, string folio_SIC_mani) {
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folio_SIC = folio_SIC;
            inValue.Body.folio_SIC_mani = folio_SIC_mani;
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoPorFolioSIC(inValue);
            return retVal.Body.MarcarComoTerminadoPorFolioSICResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.MarcarComoTerminadoPorFolioSICAsync(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest request) {
            return base.Channel.MarcarComoTerminadoPorFolioSICAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICResponse> MarcarComoTerminadoPorFolioSICAsync(string clave, string folio_SIC, string folio_SIC_mani) {
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoPorFolioSICRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folio_SIC = folio_SIC;
            inValue.Body.folio_SIC_mani = folio_SIC_mani;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoPorFolioSICAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.MarcarComoTerminado(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest request) {
            return base.Channel.MarcarComoTerminado(request);
        }
        
        public string MarcarComoTerminado(string clave, string folioSIC) {
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folioSIC = folioSIC;
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).MarcarComoTerminado(inValue);
            return retVal.Body.MarcarComoTerminadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.MarcarComoTerminadoAsync(ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest request) {
            return base.Channel.MarcarComoTerminadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoResponse> MarcarComoTerminadoAsync(string clave, string folioSIC) {
            ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.MarcarComoTerminadoRequestBody();
            inValue.Body.clave = clave;
            inValue.Body.folioSIC = folioSIC;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).MarcarComoTerminadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarFolio(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest request) {
            return base.Channel.AgregarFolio(request);
        }
        
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolio(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarFolio(inValue);
            return retVal.Body.AgregarFolioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarFolioAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest request) {
            return base.Channel.AgregarFolioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioResponse> AgregarFolioAsync(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarFolioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest request) {
            return base.Channel.AgregarFolioAvaluoCatastral(request);
        }
        
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarFolioAvaluoCatastral(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarFolioAvaluoCatastral(inValue);
            return retVal.Body.AgregarFolioAvaluoCatastralResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest request) {
            return base.Channel.AgregarFolioAvaluoCatastralAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralResponse> AgregarFolioAvaluoCatastralAsync(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarFolioAvaluoCatastralRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarFolioAvaluoCatastralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarLevantamiento(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest request) {
            return base.Channel.AgregarLevantamiento(request);
        }
        
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarLevantamiento(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarLevantamiento(inValue);
            return retVal.Body.AgregarLevantamientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarLevantamientoAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest request) {
            return base.Channel.AgregarLevantamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoResponse> AgregarLevantamientoAsync(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarLevantamientoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarLevantamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarPlanoCertificado(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest request) {
            return base.Channel.AgregarPlanoCertificado(request);
        }
        
        public ManifestacionEnLinea.ControlDeFolioDesa.FolioResp AgregarPlanoCertificado(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse retVal = ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarPlanoCertificado(inValue);
            return retVal.Body.AgregarPlanoCertificadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse> ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap.AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest request) {
            return base.Channel.AgregarPlanoCertificadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoResponse> AgregarPlanoCertificadoAsync(ManifestacionEnLinea.ControlDeFolioDesa.FolioSolicitud folio, string clave) {
            ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest inValue = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequest();
            inValue.Body = new ManifestacionEnLinea.ControlDeFolioDesa.AgregarPlanoCertificadoRequestBody();
            inValue.Body.folio = folio;
            inValue.Body.clave = clave;
            return ((ManifestacionEnLinea.ControlDeFolioDesa.CatastroControlFoliosSoap)(this)).AgregarPlanoCertificadoAsync(inValue);
        }
    }
}
